(executable
 (name test_connection)
 (modules test_connection)
 (libraries cdp cdp_lwt lwt lwt.unix yojson)
 (preprocess
  (pps lwt_ppx)))

(rule
 (alias runtest)
 (package cdp-lwt)
 (action
  (run ./test_connection.exe)))

(executable
 (name test_send_all)
 (modules test_send_all)
 (libraries cdp_lwt lwt lwt.unix)
 (preprocess
  (pps lwt_ppx)))

(executable
 (name test_reassembly)
 (modules test_reassembly)
 (libraries cdp_lwt))

(rule
 (alias runtest)
 (package cdp-lwt)
 (action
  (run ./test_reassembly.exe)))

(rule
 (alias runtest)
 (package cdp-lwt)
 (action
  (run ./test_send_all.exe)))
