(executable
 (name test_decode)
 (modules test_decode)
 (libraries cdp yojson))

(executable
 (name test_envelope)
 (modules test_envelope)
 (libraries cdp yojson))

(rule
 (alias runtest)
 (package cdp)
 (action
  (run ./test_decode.exe)))

(rule
 (alias runtest)
 (package cdp)
 (action
  (run ./test_envelope.exe)))
