(* Generated by cdp-gen from Chrome DevTools Protocol r1680125. DO NOT EDIT. *)

(* Index: users write Cdp.Network, Cdp.Page, ... *)

module Json = Cdp_json
module Base = Cdp_base
module Browser = Cdp_browser
module Browser_types = Cdp_browser_types
module Dom = Cdp_dom
module Dom_types = Cdp_dom_types
module Emulation = Cdp_emulation
module Emulation_types = Cdp_emulation_types
module Io = Cdp_io
module Io_types = Cdp_io_types
module Network = Cdp_network
module Network_types = Cdp_network_types
module Page = Cdp_page
module Page_types = Cdp_page_types
module Security = Cdp_security
module Security_types = Cdp_security_types
module Target = Cdp_target
module Target_types = Cdp_target_types
module Debugger = Cdp_debugger
module Debugger_types = Cdp_debugger_types
module Runtime = Cdp_runtime
module Runtime_types = Cdp_runtime_types
