(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)

[@@@ocaml.doc
"This domain exposes DOM read/write operations. Each DOM Node is represented with its mirror object\n\
 that has an `id`. This `id` can be used to get additional information on the Node, resolve it into\n\
 the JavaScript object wrapper, etc. It is important that client receives DOM events only for the\n\
 nodes that are known to the client. Backend keeps track of the nodes that were sent to the client\n\
 and never sends the same node twice. It is client's responsibility to collect information about\n\
 the nodes that were sent to the client. Note that `iframe` owner elements will return\n\
 corresponding document elements as their child nodes."]

open Jsonkit.Primitives

module Node_id = Cdp_base.Dom.Node_id [@@ocaml.doc "Unique DOM node identifier."]

module Backend_node_id = Cdp_base.Dom.Backend_node_id
[@@ocaml.doc "Unique DOM node identifier used to reference a node that may not have been pushed to the\nfront-end."]

module Style_sheet_id = Cdp_base.Dom.Style_sheet_id [@@ocaml.doc "Unique identifier for a CSS stylesheet."]

type backend_node = {
  node_type : int; [@key "nodeType"] [@ocaml.doc "`Node`'s nodeType."]
  node_name : string; [@key "nodeName"] [@ocaml.doc "`Node`'s nodeName."]
  backend_node_id : Cdp_base.Dom.Backend_node_id.t; [@key "backendNodeId"]
}
[@@allow_extra_fields] [@@ocaml.doc "Backend node with a friendly name."]

and pseudo_type =
  | First_line [@json.name "first-line"]
  | First_letter [@json.name "first-letter"]
  | Checkmark [@json.name "checkmark"]
  | Before [@json.name "before"]
  | After [@json.name "after"]
  | Expand_icon [@json.name "expand-icon"]
  | Picker_icon [@json.name "picker-icon"]
  | Interest_button [@json.name "interest-button"]
  | Marker [@json.name "marker"]
  | Backdrop [@json.name "backdrop"]
  | Column [@json.name "column"]
  | Selection [@json.name "selection"]
  | Search_text [@json.name "search-text"]
  | Target_text [@json.name "target-text"]
  | Spelling_error [@json.name "spelling-error"]
  | Grammar_error [@json.name "grammar-error"]
  | Highlight [@json.name "highlight"]
  | First_line_inherited [@json.name "first-line-inherited"]
  | Scroll_marker [@json.name "scroll-marker"]
  | Scroll_marker_group [@json.name "scroll-marker-group"]
  | Scroll_button [@json.name "scroll-button"]
  | Scrollbar [@json.name "scrollbar"]
  | Scrollbar_thumb [@json.name "scrollbar-thumb"]
  | Scrollbar_button [@json.name "scrollbar-button"]
  | Scrollbar_track [@json.name "scrollbar-track"]
  | Scrollbar_track_piece [@json.name "scrollbar-track-piece"]
  | Scrollbar_corner [@json.name "scrollbar-corner"]
  | Resizer [@json.name "resizer"]
  | Input_list_button [@json.name "input-list-button"]
  | View_transition [@json.name "view-transition"]
  | View_transition_group [@json.name "view-transition-group"]
  | View_transition_image_pair [@json.name "view-transition-image-pair"]
  | View_transition_group_children [@json.name "view-transition-group-children"]
  | View_transition_old [@json.name "view-transition-old"]
  | View_transition_new [@json.name "view-transition-new"]
  | Placeholder [@json.name "placeholder"]
  | File_selector_button [@json.name "file-selector-button"]
  | Details_content [@json.name "details-content"]
  | Picker [@json.name "picker"]
  | Select_listbox [@json.name "select-listbox"]
  | Permission_icon [@json.name "permission-icon"]
  | Overscroll_area_parent [@json.name "overscroll-area-parent"]
  | Overscroll_backdrop [@json.name "overscroll-backdrop"]
  | Skeleton [@json.name "skeleton"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@ocaml.doc "Pseudo element type."]

and shadow_root_type =
  | User_agent [@json.name "user-agent"]
  | Open [@json.name "open"]
  | Closed [@json.name "closed"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@ocaml.doc "Shadow root type."]

and compatibility_mode =
  | QuirksMode [@json.name "QuirksMode"]
  | LimitedQuirksMode [@json.name "LimitedQuirksMode"]
  | NoQuirksMode [@json.name "NoQuirksMode"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@ocaml.doc "Document compatibility mode."]

and physical_axes =
  | Horizontal [@json.name "Horizontal"]
  | Vertical [@json.name "Vertical"]
  | Both [@json.name "Both"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@ocaml.doc "ContainerSelector physical axes"]

and logical_axes =
  | Inline [@json.name "Inline"]
  | Block [@json.name "Block"]
  | Both [@json.name "Both"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@ocaml.doc "ContainerSelector logical axes"]

and scroll_orientation =
  | Horizontal [@json.name "horizontal"]
  | Vertical [@json.name "vertical"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@ocaml.doc "Physical scroll orientation"]

and node = {
  node_id : Cdp_base.Dom.Node_id.t;
     [@key "nodeId"]
     [@ocaml.doc
       "Node identifier that is passed into the rest of the DOM messages as the `nodeId`. Backend\n\
        will only push node with given `id` once. It is aware of all requested nodes and will only\n\
        fire DOM events for nodes known to the client."]
  parent_id : Cdp_base.Dom.Node_id.t option;
     [@key "parentId"] [@option] [@json.drop_default] [@ocaml.doc "The id of the parent node if any."]
  backend_node_id : Cdp_base.Dom.Backend_node_id.t;
     [@key "backendNodeId"] [@ocaml.doc "The BackendNodeId for this node."]
  node_type : int; [@key "nodeType"] [@ocaml.doc "`Node`'s nodeType."]
  node_name : string; [@key "nodeName"] [@ocaml.doc "`Node`'s nodeName."]
  local_name : string; [@key "localName"] [@ocaml.doc "`Node`'s localName."]
  node_value : string; [@key "nodeValue"] [@ocaml.doc "`Node`'s nodeValue."]
  child_node_count : int option;
     [@key "childNodeCount"] [@option] [@json.drop_default] [@ocaml.doc "Child count for `Container` nodes."]
  children : node list option;
     [@key "children"]
     [@option]
     [@json.drop_default]
     [@ocaml.doc "Child nodes of this node when requested with children."]
  attributes : string list option;
     [@key "attributes"]
     [@option]
     [@json.drop_default]
     [@ocaml.doc "Attributes of the `Element` node in the form of flat array `\\[name1, value1, name2, value2\\]`."]
  document_url : string option;
     [@key "documentURL"]
     [@option]
     [@json.drop_default]
     [@ocaml.doc "Document URL that `Document` or `FrameOwner` node points to."]
  base_url : string option;
     [@key "baseURL"]
     [@option]
     [@json.drop_default]
     [@ocaml.doc "Base URL that `Document` or `FrameOwner` node uses for URL completion."]
  public_id : string option; [@key "publicId"] [@option] [@json.drop_default] [@ocaml.doc "`DocumentType`'s publicId."]
  system_id : string option; [@key "systemId"] [@option] [@json.drop_default] [@ocaml.doc "`DocumentType`'s systemId."]
  internal_subset : string option;
     [@key "internalSubset"] [@option] [@json.drop_default] [@ocaml.doc "`DocumentType`'s internalSubset."]
  xml_version : string option;
     [@key "xmlVersion"]
     [@option]
     [@json.drop_default]
     [@ocaml.doc "`Document`'s XML version in case of XML documents."]
  name : string option; [@key "name"] [@option] [@json.drop_default] [@ocaml.doc "`Attr`'s name."]
  value : string option; [@key "value"] [@option] [@json.drop_default] [@ocaml.doc "`Attr`'s value."]
  pseudo_type : pseudo_type option;
     [@key "pseudoType"] [@option] [@json.drop_default] [@ocaml.doc "Pseudo element type for this node."]
  pseudo_identifier : string option;
     [@key "pseudoIdentifier"]
     [@option]
     [@json.drop_default]
     [@ocaml.doc "Pseudo element identifier for this node. Only present if there is a\nvalid pseudoType."]
  shadow_root_type : shadow_root_type option;
     [@key "shadowRootType"] [@option] [@json.drop_default] [@ocaml.doc "Shadow root type."]
  frame_id : Cdp_base.Page.Frame_id.t option;
     [@key "frameId"] [@option] [@json.drop_default] [@ocaml.doc "Frame ID for frame owner elements."]
  content_document : node option;
     [@key "contentDocument"] [@option] [@json.drop_default] [@ocaml.doc "Content document for frame owner elements."]
  shadow_roots : node list option;
     [@key "shadowRoots"] [@option] [@json.drop_default] [@ocaml.doc "Shadow root list for given element host."]
  template_content : node option;
     [@key "templateContent"]
     [@option]
     [@json.drop_default]
     [@ocaml.doc "Content document fragment for template elements."]
  pseudo_elements : node list option;
     [@key "pseudoElements"] [@option] [@json.drop_default] [@ocaml.doc "Pseudo elements associated with this node."]
  imported_document : node option;
     [@key "importedDocument"]
     [@option]
     [@json.drop_default]
     [@ocaml.deprecated "deprecated in CDP"]
     [@ocaml.doc
       "Deprecated, as the HTML Imports API has been removed (crbug.com/937746).\n\
        This property used to return the imported document for the HTMLImport links.\n\
        The property is always undefined now."]
  distributed_nodes : backend_node list option;
     [@key "distributedNodes"]
     [@option]
     [@json.drop_default]
     [@ocaml.doc "Distributed nodes for given insertion point."]
  is_svg : bool option; [@key "isSVG"] [@option] [@json.drop_default] [@ocaml.doc "Whether the node is SVG."]
  compatibility_mode : compatibility_mode option; [@key "compatibilityMode"] [@option] [@json.drop_default]
  assigned_slot : backend_node option; [@key "assignedSlot"] [@option] [@json.drop_default]
  is_scrollable : bool option;
     [@key "isScrollable"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  affected_by_starting_styles : bool option;
     [@key "affectedByStartingStyles"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  adopted_style_sheets : Cdp_base.Dom.Style_sheet_id.t list option;
     [@key "adoptedStyleSheets"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  ad_provenance : Cdp_network_types.ad_provenance option;
     [@key "adProvenance"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
}
[@@allow_extra_fields]
[@@ocaml.doc
  "DOM interaction is implemented in terms of mirror objects that represent the actual DOM nodes.\n\
   DOMNode is a base node mirror type."]

and detached_element_info = {
  tree_node : node; [@key "treeNode"]
  retained_node_ids : Cdp_base.Dom.Node_id.t list; [@key "retainedNodeIds"]
}
[@@allow_extra_fields]
[@@ocaml.doc "A structure to hold the top-level node of a detached tree and an array of its retained descendants."]

and rgba = {
  r : int; [@key "r"] [@ocaml.doc "The red component, in the \\[0-255\\] range."]
  g : int; [@key "g"] [@ocaml.doc "The green component, in the \\[0-255\\] range."]
  b : int; [@key "b"] [@ocaml.doc "The blue component, in the \\[0-255\\] range."]
  a : Cdp_json.number option;
     [@key "a"] [@option] [@json.drop_default] [@ocaml.doc "The alpha component, in the \\[0-1\\] range (default: 1)."]
}
[@@allow_extra_fields] [@@ocaml.doc "A structure holding an RGBA color."]

and quad = Cdp_json.number list
[@@ocaml.doc "An array of quad vertices, x immediately followed by y for each point, points clock-wise."]

and box_model = {
  content : quad; [@key "content"] [@ocaml.doc "Content box"]
  padding : quad; [@key "padding"] [@ocaml.doc "Padding box"]
  border : quad; [@key "border"] [@ocaml.doc "Border box"]
  margin : quad; [@key "margin"] [@ocaml.doc "Margin box"]
  width : int; [@key "width"] [@ocaml.doc "Node width"]
  height : int; [@key "height"] [@ocaml.doc "Node height"]
  shape_outside : shape_outside_info option;
     [@key "shapeOutside"] [@option] [@json.drop_default] [@ocaml.doc "Shape outside coordinates"]
}
[@@allow_extra_fields] [@@ocaml.doc "Box model."]

and shape_outside_info = {
  bounds : quad; [@key "bounds"] [@ocaml.doc "Shape bounds"]
  shape : Cdp_json.t list; [@key "shape"] [@ocaml.doc "Shape coordinate details"]
  margin_shape : Cdp_json.t list; [@key "marginShape"] [@ocaml.doc "Margin shape bounds"]
}
[@@allow_extra_fields] [@@ocaml.doc "CSS Shape Outside details."]

and rect = {
  x : Cdp_json.number; [@key "x"] [@ocaml.doc "X coordinate"]
  y : Cdp_json.number; [@key "y"] [@ocaml.doc "Y coordinate"]
  width : Cdp_json.number; [@key "width"] [@ocaml.doc "Rectangle width"]
  height : Cdp_json.number; [@key "height"] [@ocaml.doc "Rectangle height"]
}
[@@allow_extra_fields] [@@ocaml.doc "Rectangle."]

and css_computed_style_property = {
  name : string; [@key "name"] [@ocaml.doc "Computed style property name."]
  value : string; [@key "value"] [@ocaml.doc "Computed style property value."]
}
[@@allow_extra_fields] [@@deriving json, show, eq]
