(* Generated by cdp-gen from Chrome DevTools Protocol r1701330. DO NOT EDIT. *)

[@@@ocaml.doc "Supports additional targets discovery and allows to attach to them."]

open Jsonkit.Primitives

module Target_id = Cdp_base.Target.Target_id

module Session_id = Cdp_base.Target.Session_id [@@ocaml.doc "Unique identifier of attached debugging session."]

type target_info = {
  target_id : Cdp_base.Target.Target_id.t; [@key "targetId"]
  type_ : string;
     [@key "type"]
     [@ocaml.doc
       "List of types: \
        https://source.chromium.org/chromium/chromium/src/+/main:content/browser/devtools/devtools_agent_host_impl.cc?ss=chromium&q=f:devtools%20-f:out%20%22::kTypeTab%5B%5D%22"]
  title : string; [@key "title"]
  url : string; [@key "url"]
  attached : bool; [@key "attached"] [@ocaml.doc "Whether the target has an attached client."]
  parent_id : Cdp_base.Target.Target_id.t option;
     [@key "parentId"]
     [@option]
     [@json.drop_default]
     [@ocaml.doc "Id of the parent target, if any. For example, \"iframe\" target may have a \"page\" parent."]
  opener_id : Cdp_base.Target.Target_id.t option;
     [@key "openerId"] [@option] [@json.drop_default] [@ocaml.doc "Opener target Id"]
  can_access_opener : bool;
     [@key "canAccessOpener"]
     [@alert experimental "experimental in CDP, may change with Chrome"]
     [@ocaml.doc "Whether the target has access to the originating window."]
  opener_frame_id : Cdp_base.Page.Frame_id.t option;
     [@key "openerFrameId"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
     [@ocaml.doc "Frame id of originating window (is only set if target has an opener)."]
  parent_frame_id : Cdp_base.Page.Frame_id.t option;
     [@key "parentFrameId"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
     [@ocaml.doc
       "Id of the parent frame, present for \"iframe\" and \"worker\" targets. For nested workers,\n\
        this is the \"ancestor\" frame that created the first worker in the nested chain."]
  browser_context_id : Cdp_base.Browser.Browser_context_id.t option;
     [@key "browserContextId"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  subtype : string option;
     [@key "subtype"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
     [@ocaml.doc
       "Provides additional details for specific target types. For example, for\n\
        the type of \"page\", this may be set to \"prerender\"."]
  embedder_data : Cdp_json.t option;
     [@key "embedderData"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
     [@ocaml.doc "Embedder-specific target metadata. This is only set for targets of\ntype \"tab\"."]
}
[@@allow_extra_fields]

and filter_entry = {
  exclude : bool option;
     [@key "exclude"]
     [@option]
     [@json.drop_default]
     [@ocaml.doc "If set, causes exclusion of matching targets from the list."]
  type_ : string option; [@key "type"] [@option] [@json.drop_default] [@ocaml.doc "If not present, matches any type."]
}
[@@allow_extra_fields]
[@@ocaml.doc "A filter used by target query/discovery/auto-attach operations."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

and target_filter = filter_entry list
[@@ocaml.doc
  "The entries in TargetFilter are matched sequentially against targets and\n\
   the first entry that matches determines if the target is included or not,\n\
   depending on the value of `exclude` field in the entry.\n\
   If filter is not specified, the one assumed is\n\
   \\[\\{type: \"browser\", exclude: true\\}, \\{type: \"tab\", exclude: true\\}, \\{\\}\\]\n\
   (i.e. include everything but `browser` and `tab`)."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

and remote_location = {
  host : string; [@key "host"]
  port : int; [@key "port"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and window_state =
  | Normal [@json.name "normal"]
  | Minimized [@json.name "minimized"]
  | Maximized [@json.name "maximized"]
  | Fullscreen [@json.name "fullscreen"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants]
[@@ocaml.doc "The state of the target window."]
[@@alert experimental "experimental in CDP, may change with Chrome"]
[@@deriving json, show, eq]
