(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)

include Cdp_security_types
open Jsonkit.Primitives

module Disable = struct
  let name = "Security.disable"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Enable = struct
  let name = "Security.enable"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Set_ignore_certificate_errors = struct
  let name = "Security.setIgnoreCertificateErrors"

  type params = { ignore : bool [@key "ignore"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Handle_certificate_error = struct
  let name = "Security.handleCertificateError"

  type params = {
    event_id : int; [@key "eventId"]
    action : certificate_error_action; [@key "action"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Set_override_certificate_errors = struct
  let name = "Security.setOverrideCertificateErrors"

  type params = { override : bool [@key "override"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Certificate_error = struct
  let name = "Security.certificateError"

  type params = {
    event_id : int; [@key "eventId"]
    error_type : string; [@key "errorType"]
    request_url : string; [@key "requestURL"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Visible_security_state_changed = struct
  let name = "Security.visibleSecurityStateChanged"

  type params = { visible_security_state : visible_security_state [@key "visibleSecurityState"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Security_state_changed = struct
  let name = "Security.securityStateChanged"

  type params = {
    security_state : security_state; [@key "securityState"]
    scheme_is_cryptographic : bool; [@key "schemeIsCryptographic"]
    explanations : security_state_explanation list; [@key "explanations"]
    insecure_content_status : insecure_content_status; [@key "insecureContentStatus"]
    summary : string option; [@key "summary"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]
