(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)

include Cdp_emulation_types
open Jsonkit.Primitives

module Can_emulate = struct
  let name = "Emulation.canEmulate"

  type result = { result : bool [@key "result"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Clear_device_metrics_override = struct
  let name = "Emulation.clearDeviceMetricsOverride"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Clear_geolocation_override = struct
  let name = "Emulation.clearGeolocationOverride"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Reset_page_scale_factor = struct
  let name = "Emulation.resetPageScaleFactor"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_focus_emulation_enabled = struct
  let name = "Emulation.setFocusEmulationEnabled"

  type params = { enabled : bool [@key "enabled"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_auto_dark_mode_override = struct
  let name = "Emulation.setAutoDarkModeOverride"

  type params = { enabled : bool option [@key "enabled"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_cpu_throttling_rate = struct
  let name = "Emulation.setCPUThrottlingRate"

  type params = { rate : Cdp_json.number [@key "rate"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_default_background_color_override = struct
  let name = "Emulation.setDefaultBackgroundColorOverride"

  type params = { color : Cdp_dom_types.rgba option [@key "color"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_safe_area_insets_override = struct
  let name = "Emulation.setSafeAreaInsetsOverride"

  type params = { insets : safe_area_insets [@key "insets"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_virtual_keyboard_geometry_override = struct
  let name = "Emulation.setVirtualKeyboardGeometryOverride"

  type params = { keyboard_rect : Cdp_dom_types.rect option [@key "keyboardRect"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_device_metrics_override = struct
  let name = "Emulation.setDeviceMetricsOverride"

  type scrollbar_type =
    | Overlay [@json.name "overlay"]
    | Default [@json.name "default"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants]

  and viewport_meta =
    | Enable [@json.name "enable"]
    | Default [@json.name "default"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    width : int; [@key "width"]
    height : int; [@key "height"]
    device_scale_factor : Cdp_json.number; [@key "deviceScaleFactor"]
    mobile : bool; [@key "mobile"]
    scale : Cdp_json.number option;
       [@key "scale"] [@option] [@json.drop_default] [@alert experimental "experimental in CDP, may change with Chrome"]
    screen_width : int option;
       [@key "screenWidth"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    screen_height : int option;
       [@key "screenHeight"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    position_x : int option;
       [@key "positionX"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    position_y : int option;
       [@key "positionY"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    dont_set_visible_size : bool option;
       [@key "dontSetVisibleSize"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    screen_orientation : screen_orientation option; [@key "screenOrientation"] [@option] [@json.drop_default]
    viewport : Cdp_page_types.viewport option;
       [@key "viewport"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    display_feature : display_feature option;
       [@key "displayFeature"]
       [@option]
       [@json.drop_default]
       [@ocaml.deprecated "deprecated in CDP"]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    device_posture : device_posture option;
       [@key "devicePosture"]
       [@option]
       [@json.drop_default]
       [@ocaml.deprecated "deprecated in CDP"]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    scrollbar_type : scrollbar_type option;
       [@key "scrollbarType"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    screen_orientation_lock_emulation : bool option;
       [@key "screenOrientationLockEmulation"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    viewport_meta : viewport_meta option;
       [@key "viewportMeta"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_device_posture_override = struct
  let name = "Emulation.setDevicePostureOverride"

  type params = { posture : device_posture [@key "posture"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Clear_device_posture_override = struct
  let name = "Emulation.clearDevicePostureOverride"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_display_features_override = struct
  let name = "Emulation.setDisplayFeaturesOverride"

  type params = { features : display_feature list [@key "features"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Clear_display_features_override = struct
  let name = "Emulation.clearDisplayFeaturesOverride"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_scrollbars_hidden = struct
  let name = "Emulation.setScrollbarsHidden"

  type params = { hidden : bool [@key "hidden"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_document_cookie_disabled = struct
  let name = "Emulation.setDocumentCookieDisabled"

  type params = { disabled : bool [@key "disabled"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_emit_touch_events_for_mouse = struct
  let name = "Emulation.setEmitTouchEventsForMouse"

  type configuration =
    | Mobile [@json.name "mobile"]
    | Desktop [@json.name "desktop"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    enabled : bool; [@key "enabled"]
    configuration : configuration option; [@key "configuration"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_emulated_media = struct
  let name = "Emulation.setEmulatedMedia"

  type params = {
    media : string option; [@key "media"] [@option] [@json.drop_default]
    features : media_feature list option; [@key "features"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_emulated_vision_deficiency = struct
  let name = "Emulation.setEmulatedVisionDeficiency"

  type type_ =
    | None_ [@json.name "none"]
    | BlurredVision [@json.name "blurredVision"]
    | ReducedContrast [@json.name "reducedContrast"]
    | Achromatopsia [@json.name "achromatopsia"]
    | Deuteranopia [@json.name "deuteranopia"]
    | Protanopia [@json.name "protanopia"]
    | Tritanopia [@json.name "tritanopia"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = { type_ : type_ [@key "type"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_emulated_os_text_scale = struct
  let name = "Emulation.setEmulatedOSTextScale"

  type params = { scale : Cdp_json.number option [@key "scale"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_geolocation_override = struct
  let name = "Emulation.setGeolocationOverride"

  type params = {
    latitude : Cdp_json.number option; [@key "latitude"] [@option] [@json.drop_default]
    longitude : Cdp_json.number option; [@key "longitude"] [@option] [@json.drop_default]
    accuracy : Cdp_json.number option; [@key "accuracy"] [@option] [@json.drop_default]
    altitude : Cdp_json.number option; [@key "altitude"] [@option] [@json.drop_default]
    altitude_accuracy : Cdp_json.number option; [@key "altitudeAccuracy"] [@option] [@json.drop_default]
    heading : Cdp_json.number option; [@key "heading"] [@option] [@json.drop_default]
    speed : Cdp_json.number option; [@key "speed"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_overridden_sensor_information = struct
  let name = "Emulation.getOverriddenSensorInformation"

  type params = { type_ : sensor_type [@key "type"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { requested_sampling_frequency : Cdp_json.number [@key "requestedSamplingFrequency"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_sensor_override_enabled = struct
  let name = "Emulation.setSensorOverrideEnabled"

  type params = {
    enabled : bool; [@key "enabled"]
    type_ : sensor_type; [@key "type"]
    metadata : sensor_metadata option; [@key "metadata"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_sensor_override_readings = struct
  let name = "Emulation.setSensorOverrideReadings"

  type params = {
    type_ : sensor_type; [@key "type"]
    reading : sensor_reading; [@key "reading"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_pressure_source_override_enabled = struct
  let name = "Emulation.setPressureSourceOverrideEnabled"

  type params = {
    enabled : bool; [@key "enabled"]
    source : pressure_source; [@key "source"]
    metadata : pressure_metadata option; [@key "metadata"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_pressure_state_override = struct
  let name = "Emulation.setPressureStateOverride"

  type params = {
    source : pressure_source; [@key "source"]
    state : pressure_state; [@key "state"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_idle_override = struct
  let name = "Emulation.setIdleOverride"

  type params = {
    is_user_active : bool; [@key "isUserActive"]
    is_screen_unlocked : bool; [@key "isScreenUnlocked"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Clear_idle_override = struct
  let name = "Emulation.clearIdleOverride"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Set_navigator_overrides = struct
  let name = "Emulation.setNavigatorOverrides"

  type params = { platform : string [@key "platform"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_page_scale_factor = struct
  let name = "Emulation.setPageScaleFactor"

  type params = { page_scale_factor : Cdp_json.number [@key "pageScaleFactor"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_script_execution_disabled = struct
  let name = "Emulation.setScriptExecutionDisabled"

  type params = { value : bool [@key "value"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_touch_emulation_enabled = struct
  let name = "Emulation.setTouchEmulationEnabled"

  type params = {
    enabled : bool; [@key "enabled"]
    max_touch_points : int option; [@key "maxTouchPoints"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_virtual_time_policy = struct
  let name = "Emulation.setVirtualTimePolicy"

  type params = {
    policy : virtual_time_policy; [@key "policy"]
    budget : Cdp_json.number option; [@key "budget"] [@option] [@json.drop_default]
    max_virtual_time_task_starvation_count : int option;
       [@key "maxVirtualTimeTaskStarvationCount"] [@option] [@json.drop_default]
    initial_virtual_time : Cdp_base.Network.Time_since_epoch.t option;
       [@key "initialVirtualTime"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { virtual_time_ticks_base : Cdp_json.number [@key "virtualTimeTicksBase"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_locale_override = struct
  let name = "Emulation.setLocaleOverride"

  type params = { locale : string option [@key "locale"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_timezone_override = struct
  let name = "Emulation.setTimezoneOverride"

  type params = { timezone_id : string [@key "timezoneId"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_visible_size = struct
  let name = "Emulation.setVisibleSize"

  type params = {
    width : int; [@key "width"]
    height : int; [@key "height"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_disabled_image_types = struct
  let name = "Emulation.setDisabledImageTypes"

  type params = { image_types : disabled_image_type list [@key "imageTypes"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_data_saver_override = struct
  let name = "Emulation.setDataSaverOverride"

  type params = { data_saver_enabled : bool option [@key "dataSaverEnabled"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_hardware_concurrency_override = struct
  let name = "Emulation.setHardwareConcurrencyOverride"

  type params = { hardware_concurrency : int [@key "hardwareConcurrency"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_cpu_performance_override = struct
  let name = "Emulation.setCPUPerformanceOverride"

  type performance_tier =
    | Unknown [@json.name "unknown"]
    | Low [@json.name "low"]
    | Mid [@json.name "mid"]
    | High [@json.name "high"]
    | Ultra [@json.name "ultra"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = { performance_tier : performance_tier option [@key "performanceTier"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_user_agent_override = struct
  let name = "Emulation.setUserAgentOverride"

  type params = {
    user_agent : string; [@key "userAgent"]
    accept_language : string option; [@key "acceptLanguage"] [@option] [@json.drop_default]
    platform : string option; [@key "platform"] [@option] [@json.drop_default]
    user_agent_metadata : user_agent_metadata option;
       [@key "userAgentMetadata"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_automation_override = struct
  let name = "Emulation.setAutomationOverride"

  type params = { enabled : bool [@key "enabled"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_small_viewport_height_difference_override = struct
  let name = "Emulation.setSmallViewportHeightDifferenceOverride"

  type params = { difference : int [@key "difference"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_screen_infos = struct
  let name = "Emulation.getScreenInfos"

  type result = { screen_infos : screen_info list [@key "screenInfos"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Add_screen = struct
  let name = "Emulation.addScreen"

  type params = {
    left : int; [@key "left"]
    top : int; [@key "top"]
    width : int; [@key "width"]
    height : int; [@key "height"]
    work_area_insets : work_area_insets option; [@key "workAreaInsets"] [@option] [@json.drop_default]
    device_pixel_ratio : Cdp_json.number option; [@key "devicePixelRatio"] [@option] [@json.drop_default]
    rotation : int option; [@key "rotation"] [@option] [@json.drop_default]
    color_depth : int option; [@key "colorDepth"] [@option] [@json.drop_default]
    label : string option; [@key "label"] [@option] [@json.drop_default]
    is_internal : bool option; [@key "isInternal"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { screen_info : screen_info [@key "screenInfo"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Update_screen = struct
  let name = "Emulation.updateScreen"

  type params = {
    screen_id : Cdp_base.Emulation.Screen_id.t; [@key "screenId"]
    left : int option; [@key "left"] [@option] [@json.drop_default]
    top : int option; [@key "top"] [@option] [@json.drop_default]
    width : int option; [@key "width"] [@option] [@json.drop_default]
    height : int option; [@key "height"] [@option] [@json.drop_default]
    work_area_insets : work_area_insets option; [@key "workAreaInsets"] [@option] [@json.drop_default]
    device_pixel_ratio : Cdp_json.number option; [@key "devicePixelRatio"] [@option] [@json.drop_default]
    rotation : int option; [@key "rotation"] [@option] [@json.drop_default]
    color_depth : int option; [@key "colorDepth"] [@option] [@json.drop_default]
    label : string option; [@key "label"] [@option] [@json.drop_default]
    is_internal : bool option; [@key "isInternal"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { screen_info : screen_info [@key "screenInfo"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Remove_screen = struct
  let name = "Emulation.removeScreen"

  type params = { screen_id : Cdp_base.Emulation.Screen_id.t [@key "screenId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_primary_screen = struct
  let name = "Emulation.setPrimaryScreen"

  type params = { screen_id : Cdp_base.Emulation.Screen_id.t [@key "screenId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Virtual_time_budget_expired = struct
  let name = "Emulation.virtualTimeBudgetExpired"

  type params = unit [@@deriving show, eq]

  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Screen_orientation_lock_changed = struct
  let name = "Emulation.screenOrientationLockChanged"

  type params = {
    locked : bool; [@key "locked"]
    orientation : screen_orientation option; [@key "orientation"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]
