(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)
(* Sealed modules for every primitive alias type. This file depends on
   nothing, so alias references can never create a module cycle. *)

module Browser = struct
  module Browser_context_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@alert experimental "experimental in CDP, may change with Chrome"]

  module Window_id : sig
    type t
    val of_int : int -> t
    val to_int : t -> int
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = int
    let of_int value = value
    let to_int value = value
    let equal = Int.equal
    let compare = Int.compare
    let show (value : t) = string_of_int value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.int_of_json
    let to_json = Jsonkit.Primitives.int_to_json
  end
  [@@alert experimental "experimental in CDP, may change with Chrome"]
end

module Dom = struct
  module Node_id : sig
    type t
    val of_int : int -> t
    val to_int : t -> int
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = int
    let of_int value = value
    let to_int value = value
    let equal = Int.equal
    let compare = Int.compare
    let show (value : t) = string_of_int value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.int_of_json
    let to_json = Jsonkit.Primitives.int_to_json
  end
  [@@ocaml.doc "Unique DOM node identifier."]

  module Backend_node_id : sig
    type t
    val of_int : int -> t
    val to_int : t -> int
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = int
    let of_int value = value
    let to_int value = value
    let equal = Int.equal
    let compare = Int.compare
    let show (value : t) = string_of_int value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.int_of_json
    let to_json = Jsonkit.Primitives.int_to_json
  end
  [@@ocaml.doc "Unique DOM node identifier used to reference a node that may not have been pushed to the\nfront-end."]

  module Style_sheet_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "Unique identifier for a CSS stylesheet."]
end

module Emulation = struct
  module Screen_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@alert experimental "experimental in CDP, may change with Chrome"]
end

module Io = struct
  module Stream_handle : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc
    "This is either obtained from another method or specified as `blob:<uuid>` where\n`<uuid>` is an UUID of a Blob."]
end

module Network = struct
  module Loader_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "Unique loader identifier."]

  module Request_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc
    "Unique network request identifier.\n\
     Note that this does not identify individual HTTP requests that are part of\n\
     a network request."]

  module Time_since_epoch : sig
    type t
    val of_float : float -> t
    val to_float : t -> float
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = float
    let of_float value = value
    let to_float value = value
    let equal = Float.equal
    let compare = Float.compare
    let show (value : t) = string_of_float value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Cdp_json.number_of_json
    let to_json = Cdp_json.number_to_json
  end
  [@@ocaml.doc "UTC time in seconds, counted from January 1, 1970."]

  module Monotonic_time : sig
    type t
    val of_float : float -> t
    val to_float : t -> float
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = float
    let of_float value = value
    let to_float value = value
    let equal = Float.equal
    let compare = Float.compare
    let show (value : t) = string_of_float value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Cdp_json.number_of_json
    let to_json = Cdp_json.number_to_json
  end
  [@@ocaml.doc "Monotonically increasing time in seconds since an arbitrary point in the past."]

  module Report_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@alert experimental "experimental in CDP, may change with Chrome"]

  module Device_bound_session_event_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "A unique identifier for a device bound session event."]
  [@@alert experimental "experimental in CDP, may change with Chrome"]
end

module Page = struct
  module Frame_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "Unique frame identifier."]

  module Script_identifier : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "Unique script identifier."]
end

module Security = struct
  module Certificate_id : sig
    type t
    val of_int : int -> t
    val to_int : t -> int
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = int
    let of_int value = value
    let to_int value = value
    let equal = Int.equal
    let compare = Int.compare
    let show (value : t) = string_of_int value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.int_of_json
    let to_json = Jsonkit.Primitives.int_to_json
  end
  [@@ocaml.doc "An internal certificate ID value."]
end

module Target = struct
  module Target_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end

  module Session_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "Unique identifier of attached debugging session."]
end

module Debugger = struct
  module Breakpoint_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "Breakpoint identifier."]

  module Call_frame_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "Call frame identifier."]
end

module Runtime = struct
  module Script_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "Unique script identifier."]

  module Remote_object_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "Unique object identifier."]

  module Unserializable_value : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc
    "Primitive value which cannot be JSON-stringified. Includes values `-0`, `NaN`, `Infinity`,\n\
     `-Infinity`, and bigint literals."]

  module Execution_context_id : sig
    type t
    val of_int : int -> t
    val to_int : t -> int
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = int
    let of_int value = value
    let to_int value = value
    let equal = Int.equal
    let compare = Int.compare
    let show (value : t) = string_of_int value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.int_of_json
    let to_json = Jsonkit.Primitives.int_to_json
  end
  [@@ocaml.doc "Id of an execution context."]

  module Timestamp : sig
    type t
    val of_float : float -> t
    val to_float : t -> float
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = float
    let of_float value = value
    let to_float value = value
    let equal = Float.equal
    let compare = Float.compare
    let show (value : t) = string_of_float value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Cdp_json.number_of_json
    let to_json = Cdp_json.number_to_json
  end
  [@@ocaml.doc "Number of milliseconds since epoch."]

  module Time_delta : sig
    type t
    val of_float : float -> t
    val to_float : t -> float
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = float
    let of_float value = value
    let to_float value = value
    let equal = Float.equal
    let compare = Float.compare
    let show (value : t) = string_of_float value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Cdp_json.number_of_json
    let to_json = Cdp_json.number_to_json
  end
  [@@ocaml.doc "Number of milliseconds."]

  module Unique_debugger_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@ocaml.doc "Unique identifier of current debugger."]
  [@@alert experimental "experimental in CDP, may change with Chrome"]
end
