(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)

open Jsonkit.Primitives

module Node_id = Cdp_base.Dom.Node_id
module Backend_node_id = Cdp_base.Dom.Backend_node_id
module Style_sheet_id = Cdp_base.Dom.Style_sheet_id

type backend_node = {
  node_type : int; [@key "nodeType"]
  node_name : string; [@key "nodeName"]
  backend_node_id : Cdp_base.Dom.Backend_node_id.t; [@key "backendNodeId"]
}
[@@allow_extra_fields]

and pseudo_type =
  | First_line [@json.name "first-line"]
  | First_letter [@json.name "first-letter"]
  | Checkmark [@json.name "checkmark"]
  | Before [@json.name "before"]
  | After [@json.name "after"]
  | Expand_icon [@json.name "expand-icon"]
  | Picker_icon [@json.name "picker-icon"]
  | Interest_button [@json.name "interest-button"]
  | Marker [@json.name "marker"]
  | Backdrop [@json.name "backdrop"]
  | Column [@json.name "column"]
  | Selection [@json.name "selection"]
  | Search_text [@json.name "search-text"]
  | Target_text [@json.name "target-text"]
  | Spelling_error [@json.name "spelling-error"]
  | Grammar_error [@json.name "grammar-error"]
  | Highlight [@json.name "highlight"]
  | First_line_inherited [@json.name "first-line-inherited"]
  | Scroll_marker [@json.name "scroll-marker"]
  | Scroll_marker_group [@json.name "scroll-marker-group"]
  | Scroll_button [@json.name "scroll-button"]
  | Scrollbar [@json.name "scrollbar"]
  | Scrollbar_thumb [@json.name "scrollbar-thumb"]
  | Scrollbar_button [@json.name "scrollbar-button"]
  | Scrollbar_track [@json.name "scrollbar-track"]
  | Scrollbar_track_piece [@json.name "scrollbar-track-piece"]
  | Scrollbar_corner [@json.name "scrollbar-corner"]
  | Resizer [@json.name "resizer"]
  | Input_list_button [@json.name "input-list-button"]
  | View_transition [@json.name "view-transition"]
  | View_transition_group [@json.name "view-transition-group"]
  | View_transition_image_pair [@json.name "view-transition-image-pair"]
  | View_transition_group_children [@json.name "view-transition-group-children"]
  | View_transition_old [@json.name "view-transition-old"]
  | View_transition_new [@json.name "view-transition-new"]
  | Placeholder [@json.name "placeholder"]
  | File_selector_button [@json.name "file-selector-button"]
  | Details_content [@json.name "details-content"]
  | Picker [@json.name "picker"]
  | Select_listbox [@json.name "select-listbox"]
  | Permission_icon [@json.name "permission-icon"]
  | Overscroll_area_parent [@json.name "overscroll-area-parent"]
  | Overscroll_backdrop [@json.name "overscroll-backdrop"]
  | Skeleton [@json.name "skeleton"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants]

and shadow_root_type =
  | User_agent [@json.name "user-agent"]
  | Open [@json.name "open"]
  | Closed [@json.name "closed"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants]

and compatibility_mode =
  | QuirksMode [@json.name "QuirksMode"]
  | LimitedQuirksMode [@json.name "LimitedQuirksMode"]
  | NoQuirksMode [@json.name "NoQuirksMode"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants]

and physical_axes =
  | Horizontal [@json.name "Horizontal"]
  | Vertical [@json.name "Vertical"]
  | Both [@json.name "Both"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants]

and logical_axes =
  | Inline [@json.name "Inline"]
  | Block [@json.name "Block"]
  | Both [@json.name "Both"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants]

and scroll_orientation =
  | Horizontal [@json.name "horizontal"]
  | Vertical [@json.name "vertical"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants]

and node = {
  node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
  parent_id : Cdp_base.Dom.Node_id.t option; [@key "parentId"] [@option] [@json.drop_default]
  backend_node_id : Cdp_base.Dom.Backend_node_id.t; [@key "backendNodeId"]
  node_type : int; [@key "nodeType"]
  node_name : string; [@key "nodeName"]
  local_name : string; [@key "localName"]
  node_value : string; [@key "nodeValue"]
  child_node_count : int option; [@key "childNodeCount"] [@option] [@json.drop_default]
  children : node list option; [@key "children"] [@option] [@json.drop_default]
  attributes : string list option; [@key "attributes"] [@option] [@json.drop_default]
  document_url : string option; [@key "documentURL"] [@option] [@json.drop_default]
  base_url : string option; [@key "baseURL"] [@option] [@json.drop_default]
  public_id : string option; [@key "publicId"] [@option] [@json.drop_default]
  system_id : string option; [@key "systemId"] [@option] [@json.drop_default]
  internal_subset : string option; [@key "internalSubset"] [@option] [@json.drop_default]
  xml_version : string option; [@key "xmlVersion"] [@option] [@json.drop_default]
  name : string option; [@key "name"] [@option] [@json.drop_default]
  value : string option; [@key "value"] [@option] [@json.drop_default]
  pseudo_type : pseudo_type option; [@key "pseudoType"] [@option] [@json.drop_default]
  pseudo_identifier : string option; [@key "pseudoIdentifier"] [@option] [@json.drop_default]
  shadow_root_type : shadow_root_type option; [@key "shadowRootType"] [@option] [@json.drop_default]
  frame_id : Cdp_base.Page.Frame_id.t option; [@key "frameId"] [@option] [@json.drop_default]
  content_document : node option; [@key "contentDocument"] [@option] [@json.drop_default]
  shadow_roots : node list option; [@key "shadowRoots"] [@option] [@json.drop_default]
  template_content : node option; [@key "templateContent"] [@option] [@json.drop_default]
  pseudo_elements : node list option; [@key "pseudoElements"] [@option] [@json.drop_default]
  imported_document : node option;
     [@key "importedDocument"] [@option] [@json.drop_default] [@ocaml.deprecated "deprecated in CDP"]
  distributed_nodes : backend_node list option; [@key "distributedNodes"] [@option] [@json.drop_default]
  is_svg : bool option; [@key "isSVG"] [@option] [@json.drop_default]
  compatibility_mode : compatibility_mode option; [@key "compatibilityMode"] [@option] [@json.drop_default]
  assigned_slot : backend_node option; [@key "assignedSlot"] [@option] [@json.drop_default]
  is_scrollable : bool option;
     [@key "isScrollable"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  affected_by_starting_styles : bool option;
     [@key "affectedByStartingStyles"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  adopted_style_sheets : Cdp_base.Dom.Style_sheet_id.t list option;
     [@key "adoptedStyleSheets"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  ad_provenance : Cdp_network_types.ad_provenance option;
     [@key "adProvenance"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
}
[@@allow_extra_fields]

and detached_element_info = {
  tree_node : node; [@key "treeNode"]
  retained_node_ids : Cdp_base.Dom.Node_id.t list; [@key "retainedNodeIds"]
}
[@@allow_extra_fields]

and rgba = {
  r : int; [@key "r"]
  g : int; [@key "g"]
  b : int; [@key "b"]
  a : Cdp_json.number option; [@key "a"] [@option] [@json.drop_default]
}
[@@allow_extra_fields]

and quad = Cdp_json.number list

and box_model = {
  content : quad; [@key "content"]
  padding : quad; [@key "padding"]
  border : quad; [@key "border"]
  margin : quad; [@key "margin"]
  width : int; [@key "width"]
  height : int; [@key "height"]
  shape_outside : shape_outside_info option; [@key "shapeOutside"] [@option] [@json.drop_default]
}
[@@allow_extra_fields]

and shape_outside_info = {
  bounds : quad; [@key "bounds"]
  shape : Cdp_json.t list; [@key "shape"]
  margin_shape : Cdp_json.t list; [@key "marginShape"]
}
[@@allow_extra_fields]

and rect = {
  x : Cdp_json.number; [@key "x"]
  y : Cdp_json.number; [@key "y"]
  width : Cdp_json.number; [@key "width"]
  height : Cdp_json.number; [@key "height"]
}
[@@allow_extra_fields]

and css_computed_style_property = {
  name : string; [@key "name"]
  value : string; [@key "value"]
}
[@@allow_extra_fields] [@@deriving json, show, eq]
