(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)

[@@@ocaml.doc
"Runtime domain exposes JavaScript runtime by means of remote evaluation and mirror objects.\n\
 Evaluation results are returned as mirror object that expose object type, string representation\n\
 and unique identifier that can be used for further object reference. Original objects are\n\
 maintained in memory unless they are either explicitly released or are released along with the\n\
 other objects in their object group."]

include Cdp_runtime_types
open Jsonkit.Primitives

module Await_promise = struct
  let name = "Runtime.awaitPromise"

  type params = {
    promise_object_id : Cdp_base.Runtime.Remote_object_id.t;
       [@key "promiseObjectId"] [@ocaml.doc "Identifier of the promise."]
    return_by_value : bool option;
       [@key "returnByValue"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether the result is expected to be a JSON object that should be sent by value."]
    generate_preview : bool option;
       [@key "generatePreview"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether preview should be generated for the result."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    result : remote_object;
       [@key "result"] [@ocaml.doc "Promise result. Will contain rejected value if promise was rejected."]
    exception_details : exception_details option;
       [@key "exceptionDetails"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Exception details if stack strace is available."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Add handler to promise with given promise object id."]

module Call_function_on = struct
  let name = "Runtime.callFunctionOn"

  type params = {
    function_declaration : string; [@key "functionDeclaration"] [@ocaml.doc "Declaration of the function to call."]
    object_id : Cdp_base.Runtime.Remote_object_id.t option;
       [@key "objectId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Identifier of the object to call function on. Either objectId or executionContextId should\nbe specified."]
    arguments : call_argument list option;
       [@key "arguments"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Call arguments. All call arguments must belong to the same JavaScript world as the target\nobject."]
    silent : bool option;
       [@key "silent"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "In silent mode exceptions thrown during evaluation are not reported and do not pause\n\
          execution. Overrides `setPauseOnException` state."]
    return_by_value : bool option;
       [@key "returnByValue"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Whether the result is expected to be a JSON object which should be sent by value.\n\
          Can be overriden by `serializationOptions`."]
    generate_preview : bool option;
       [@key "generatePreview"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Whether preview should be generated for the result."]
    user_gesture : bool option;
       [@key "userGesture"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether execution should be treated as initiated by user in the UI."]
    await_promise : bool option;
       [@key "awaitPromise"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether execution should `await` for resulting value and return once awaited promise is\nresolved."]
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t option;
       [@key "executionContextId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Specifies execution context which global object will be used to call function on. Either\n\
          executionContextId or objectId should be specified."]
    object_group : string option;
       [@key "objectGroup"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Symbolic group name that can be used to release multiple objects. If objectGroup is not\n\
          specified and objectId is, objectGroup will be inherited from object."]
    throw_on_side_effect : bool option;
       [@key "throwOnSideEffect"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Whether to throw an exception if side effect cannot be ruled out during evaluation."]
    unique_context_id : string option;
       [@key "uniqueContextId"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc
         "An alternative way to specify the execution context to call function on.\n\
          Compared to contextId that may be reused across processes, this is guaranteed to be\n\
          system-unique, so it can be used to prevent accidental function call\n\
          in context different than intended (e.g. as a result of navigation across process\n\
          boundaries).\n\
          This is mutually exclusive with `executionContextId`."]
    serialization_options : serialization_options option;
       [@key "serializationOptions"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Specifies the result serialization. If provided, overrides\n`generatePreview` and `returnByValue`."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    result : remote_object; [@key "result"] [@ocaml.doc "Call result."]
    exception_details : exception_details option;
       [@key "exceptionDetails"] [@option] [@json.drop_default] [@ocaml.doc "Exception details."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Calls function with given declaration on the given object. Object group of the result is\n\
   inherited from the target object."]

module Compile_script = struct
  let name = "Runtime.compileScript"

  type params = {
    expression : string; [@key "expression"] [@ocaml.doc "Expression to compile."]
    source_url : string; [@key "sourceURL"] [@ocaml.doc "Source url to be set for the script."]
    persist_script : bool;
       [@key "persistScript"] [@ocaml.doc "Specifies whether the compiled script should be persisted."]
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t option;
       [@key "executionContextId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Specifies in which execution context to perform script run. If the parameter is omitted the\n\
          evaluation will be performed in the context of the inspected page."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    script_id : Cdp_base.Runtime.Script_id.t option;
       [@key "scriptId"] [@option] [@json.drop_default] [@ocaml.doc "Id of the script."]
    exception_details : exception_details option;
       [@key "exceptionDetails"] [@option] [@json.drop_default] [@ocaml.doc "Exception details."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Compiles expression."]

module Disable = struct
  let name = "Runtime.disable"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Disables reporting of execution contexts creation."]

module Discard_console_entries = struct
  let name = "Runtime.discardConsoleEntries"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Discards collected exceptions and console API calls."]

module Enable = struct
  let name = "Runtime.enable"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc
  "Enables reporting of execution contexts creation by means of `executionContextCreated` event.\n\
   When the reporting gets enabled the event will be sent immediately for each existing execution\n\
   context."]

module Evaluate = struct
  let name = "Runtime.evaluate"

  type params = {
    expression : string; [@key "expression"] [@ocaml.doc "Expression to evaluate."]
    object_group : string option;
       [@key "objectGroup"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Symbolic group name that can be used to release multiple objects."]
    include_command_line_api : bool option;
       [@key "includeCommandLineAPI"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Determines whether Command Line API should be available during the evaluation."]
    silent : bool option;
       [@key "silent"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "In silent mode exceptions thrown during evaluation are not reported and do not pause\n\
          execution. Overrides `setPauseOnException` state."]
    context_id : Cdp_base.Runtime.Execution_context_id.t option;
       [@key "contextId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Specifies in which execution context to perform evaluation. If the parameter is omitted the\n\
          evaluation will be performed in the context of the inspected page.\n\
          This is mutually exclusive with `uniqueContextId`, which offers an\n\
          alternative way to identify the execution context that is more reliable\n\
          in a multi-process environment."]
    return_by_value : bool option;
       [@key "returnByValue"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether the result is expected to be a JSON object that should be sent by value."]
    generate_preview : bool option;
       [@key "generatePreview"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Whether preview should be generated for the result."]
    user_gesture : bool option;
       [@key "userGesture"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether execution should be treated as initiated by user in the UI."]
    await_promise : bool option;
       [@key "awaitPromise"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether execution should `await` for resulting value and return once awaited promise is\nresolved."]
    throw_on_side_effect : bool option;
       [@key "throwOnSideEffect"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc
         "Whether to throw an exception if side effect cannot be ruled out during evaluation.\n\
          This implies `disableBreaks` below."]
    timeout : Cdp_base.Runtime.Time_delta.t option;
       [@key "timeout"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Terminate execution after timing out (number of milliseconds)."]
    disable_breaks : bool option;
       [@key "disableBreaks"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Disable breakpoints during execution."]
    repl_mode : bool option;
       [@key "replMode"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc
         "Setting this flag to true enables `let` re-declaration and top-level `await`.\n\
          Note that `let` variables can only be re-declared if they originate from\n\
          `replMode` themselves."]
    allow_unsafe_eval_blocked_by_csp : bool option;
       [@key "allowUnsafeEvalBlockedByCSP"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc
         "The Content Security Policy (CSP) for the target might block 'unsafe-eval'\n\
          which includes eval(), Function(), setTimeout() and setInterval()\n\
          when called with non-callable arguments. This flag bypasses CSP for this\n\
          evaluation and allows unsafe-eval. Defaults to true."]
    unique_context_id : string option;
       [@key "uniqueContextId"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc
         "An alternative way to specify the execution context to evaluate in.\n\
          Compared to contextId that may be reused across processes, this is guaranteed to be\n\
          system-unique, so it can be used to prevent accidental evaluation of the expression\n\
          in context different than intended (e.g. as a result of navigation across process\n\
          boundaries).\n\
          This is mutually exclusive with `contextId`."]
    serialization_options : serialization_options option;
       [@key "serializationOptions"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Specifies the result serialization. If provided, overrides\n`generatePreview` and `returnByValue`."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    result : remote_object; [@key "result"] [@ocaml.doc "Evaluation result."]
    exception_details : exception_details option;
       [@key "exceptionDetails"] [@option] [@json.drop_default] [@ocaml.doc "Exception details."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Evaluates expression on global object."]

module Get_isolate_id = struct
  let name = "Runtime.getIsolateId"

  type result = { id : string [@key "id"] [@ocaml.doc "The isolate id."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Returns the isolate id."] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_heap_usage = struct
  let name = "Runtime.getHeapUsage"

  type result = {
    used_size : Cdp_json.number; [@key "usedSize"] [@ocaml.doc "Used JavaScript heap size in bytes."]
    total_size : Cdp_json.number; [@key "totalSize"] [@ocaml.doc "Allocated JavaScript heap size in bytes."]
    embedder_heap_used_size : Cdp_json.number;
       [@key "embedderHeapUsedSize"] [@ocaml.doc "Used size in bytes in the embedder's garbage-collected heap."]
    backing_storage_size : Cdp_json.number;
       [@key "backingStorageSize"]
       [@ocaml.doc "Size in bytes of backing storage for array buffers and external strings."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc
  "Returns the JavaScript heap usage.\n\
   It is the total usage of the corresponding isolate not scoped to a particular Runtime."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_properties = struct
  let name = "Runtime.getProperties"

  type params = {
    object_id : Cdp_base.Runtime.Remote_object_id.t;
       [@key "objectId"] [@ocaml.doc "Identifier of the object to return properties for."]
    own_properties : bool option;
       [@key "ownProperties"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "If true, returns properties belonging only to the element itself, not to its prototype\nchain."]
    accessor_properties_only : bool option;
       [@key "accessorPropertiesOnly"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc
         "If true, returns accessor properties (with getter/setter) only; internal properties are not\nreturned either."]
    generate_preview : bool option;
       [@key "generatePreview"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Whether preview should be generated for the results."]
    non_indexed_properties_only : bool option;
       [@key "nonIndexedPropertiesOnly"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "If true, returns non-indexed properties only."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    result : property_descriptor list; [@key "result"] [@ocaml.doc "Object properties."]
    internal_properties : internal_property_descriptor list option;
       [@key "internalProperties"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Internal object properties (only of the element itself)."]
    private_properties : private_property_descriptor list option;
       [@key "privateProperties"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Object private properties."]
    exception_details : exception_details option;
       [@key "exceptionDetails"] [@option] [@json.drop_default] [@ocaml.doc "Exception details."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Returns properties of a given object. Object group of the result is inherited from the target\nobject."]

module Global_lexical_scope_names = struct
  let name = "Runtime.globalLexicalScopeNames"

  type params = {
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t option;
       [@key "executionContextId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Specifies in which execution context to lookup global scope variables."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { names : string list [@key "names"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Returns all let, const and class variables from global scope."]

module Query_objects = struct
  let name = "Runtime.queryObjects"

  type params = {
    prototype_object_id : Cdp_base.Runtime.Remote_object_id.t;
       [@key "prototypeObjectId"] [@ocaml.doc "Identifier of the prototype to return objects for."]
    object_group : string option;
       [@key "objectGroup"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Symbolic group name that can be used to release the results."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { objects : remote_object [@key "objects"] [@ocaml.doc "Array with objects."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Release_object = struct
  let name = "Runtime.releaseObject"

  type params = {
    object_id : Cdp_base.Runtime.Remote_object_id.t;
       [@key "objectId"] [@ocaml.doc "Identifier of the object to release."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Releases remote object with given id."]

module Release_object_group = struct
  let name = "Runtime.releaseObjectGroup"

  type params = { object_group : string [@key "objectGroup"] [@ocaml.doc "Symbolic object group name."] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Releases all remote objects that belong to a given group."]

module Run_if_waiting_for_debugger = struct
  let name = "Runtime.runIfWaitingForDebugger"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Tells inspected instance to run if it was waiting for debugger to attach."]

module Run_script = struct
  let name = "Runtime.runScript"

  type params = {
    script_id : Cdp_base.Runtime.Script_id.t; [@key "scriptId"] [@ocaml.doc "Id of the script to run."]
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t option;
       [@key "executionContextId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Specifies in which execution context to perform script run. If the parameter is omitted the\n\
          evaluation will be performed in the context of the inspected page."]
    object_group : string option;
       [@key "objectGroup"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Symbolic group name that can be used to release multiple objects."]
    silent : bool option;
       [@key "silent"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "In silent mode exceptions thrown during evaluation are not reported and do not pause\n\
          execution. Overrides `setPauseOnException` state."]
    include_command_line_api : bool option;
       [@key "includeCommandLineAPI"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Determines whether Command Line API should be available during the evaluation."]
    return_by_value : bool option;
       [@key "returnByValue"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether the result is expected to be a JSON object which should be sent by value."]
    generate_preview : bool option;
       [@key "generatePreview"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether preview should be generated for the result."]
    await_promise : bool option;
       [@key "awaitPromise"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether execution should `await` for resulting value and return once awaited promise is\nresolved."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    result : remote_object; [@key "result"] [@ocaml.doc "Run result."]
    exception_details : exception_details option;
       [@key "exceptionDetails"] [@option] [@json.drop_default] [@ocaml.doc "Exception details."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Runs script with given id in a given context."]

module Set_async_call_stack_depth = struct
  let name = "Runtime.setAsyncCallStackDepth"

  type params = {
    max_depth : int;
       [@key "maxDepth"]
       [@ocaml.doc
         "Maximum depth of async call stacks. Setting to `0` will effectively disable collecting async\n\
          call stacks (default)."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Enables or disables async call stacks tracking."]
[@@alert redirected "redirected to the Debugger domain in CDP"]

module Set_custom_object_formatter_enabled = struct
  let name = "Runtime.setCustomObjectFormatterEnabled"

  type params = { enabled : bool [@key "enabled"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_max_call_stack_size_to_capture = struct
  let name = "Runtime.setMaxCallStackSizeToCapture"

  type params = { size : int [@key "size"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Terminate_execution = struct
  let name = "Runtime.terminateExecution"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc
  "Terminate current or next JavaScript execution.\n\
   Will cancel the termination when the outer-most script execution ends."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Add_binding = struct
  let name = "Runtime.addBinding"

  type params = {
    name : string; [@key "name"]
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t option;
       [@key "executionContextId"]
       [@option]
       [@json.drop_default]
       [@ocaml.deprecated "deprecated in CDP"]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc
         "If specified, the binding would only be exposed to the specified\n\
          execution context. If omitted and `executionContextName` is not set,\n\
          the binding is exposed to all execution contexts of the target.\n\
          This parameter is mutually exclusive with `executionContextName`.\n\
          Deprecated in favor of `executionContextName` due to an unclear use case\n\
          and bugs in implementation (crbug.com/1169639). `executionContextId` will be\n\
          removed in the future."]
    execution_context_name : string option;
       [@key "executionContextName"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "If specified, the binding is exposed to the executionContext with\n\
          matching name, even for contexts created after the binding is added.\n\
          See also `ExecutionContext.name` and `worldName` parameter to\n\
          `Page.addScriptToEvaluateOnNewDocument`.\n\
          This parameter is mutually exclusive with `executionContextId`."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "If executionContextId is empty, adds binding with the given name on the\n\
   global objects of all inspected contexts, including those created later,\n\
   bindings survive reloads.\n\
   Binding function takes exactly one argument, this argument should be string,\n\
   in case of any other input, function throws an exception.\n\
   Each binding function call produces Runtime.bindingCalled notification."]

module Remove_binding = struct
  let name = "Runtime.removeBinding"

  type params = { name : string [@key "name"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "This method does not remove binding function from global object but\n\
   unsubscribes current runtime agent from Runtime.bindingCalled notifications."]

module Get_exception_details = struct
  let name = "Runtime.getExceptionDetails"

  type params = {
    error_object_id : Cdp_base.Runtime.Remote_object_id.t;
       [@key "errorObjectId"] [@ocaml.doc "The error object for which to resolve the exception details."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    exception_details : exception_details option; [@key "exceptionDetails"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "This method tries to lookup and populate exception details for a\n\
   JavaScript Error object.\n\
   Note that the stackTrace portion of the resulting exceptionDetails will\n\
   only be populated if the Runtime domain was enabled at the time when the\n\
   Error was thrown."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Binding_called = struct
  let name = "Runtime.bindingCalled"

  type params = {
    name : string; [@key "name"]
    payload : string; [@key "payload"]
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t;
       [@key "executionContextId"] [@ocaml.doc "Identifier of the context where the call was made."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Notification is issued every time when binding is called."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Console_api_called = struct
  let name = "Runtime.consoleAPICalled"

  type type_ =
    | Log [@json.name "log"]
    | Debug [@json.name "debug"]
    | Info [@json.name "info"]
    | Error_ [@json.name "error"]
    | Warning [@json.name "warning"]
    | Dir [@json.name "dir"]
    | Dirxml [@json.name "dirxml"]
    | Table [@json.name "table"]
    | Trace [@json.name "trace"]
    | Clear [@json.name "clear"]
    | StartGroup [@json.name "startGroup"]
    | StartGroupCollapsed [@json.name "startGroupCollapsed"]
    | EndGroup [@json.name "endGroup"]
    | Assert [@json.name "assert"]
    | Profile [@json.name "profile"]
    | ProfileEnd [@json.name "profileEnd"]
    | Count [@json.name "count"]
    | TimeEnd [@json.name "timeEnd"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    type_ : type_; [@key "type"] [@ocaml.doc "Type of the call."]
    args : remote_object list; [@key "args"] [@ocaml.doc "Call arguments."]
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t;
       [@key "executionContextId"] [@ocaml.doc "Identifier of the context where the call was made."]
    timestamp : Cdp_base.Runtime.Timestamp.t; [@key "timestamp"] [@ocaml.doc "Call timestamp."]
    stack_trace : stack_trace option;
       [@key "stackTrace"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Stack trace captured when the call was made. The async stack chain is automatically reported for\n\
          the following call types: `assert`, `error`, `trace`, `warning`. For other types the async call\n\
          chain can be retrieved using `Debugger.getStackTrace` and `stackTrace.parentId` field."]
    context : string option;
       [@key "context"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc
         "Console context descriptor for calls on non-default console context (not console.*):\n\
          'anonymous#unique-logger-id' for call on unnamed context, 'name#unique-logger-id' for call\n\
          on named context."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Issued when console API was called."]

module Exception_revoked = struct
  let name = "Runtime.exceptionRevoked"

  type params = {
    reason : string; [@key "reason"] [@ocaml.doc "Reason describing why exception was revoked."]
    exception_id : int;
       [@key "exceptionId"] [@ocaml.doc "The id of revoked exception, as reported in `exceptionThrown`."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Issued when unhandled exception was revoked."]

module Exception_thrown = struct
  let name = "Runtime.exceptionThrown"

  type params = {
    timestamp : Cdp_base.Runtime.Timestamp.t; [@key "timestamp"] [@ocaml.doc "Timestamp of the exception."]
    exception_details : exception_details; [@key "exceptionDetails"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Issued when exception was thrown and unhandled."]

module Execution_context_created = struct
  let name = "Runtime.executionContextCreated"

  type params = {
    context : execution_context_description; [@key "context"] [@ocaml.doc "A newly created execution context."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Issued when new execution context is created."]

module Execution_context_destroyed = struct
  let name = "Runtime.executionContextDestroyed"

  type params = {
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t;
       [@key "executionContextId"] [@ocaml.deprecated "deprecated in CDP"] [@ocaml.doc "Id of the destroyed context"]
    execution_context_unique_id : string;
       [@key "executionContextUniqueId"]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Unique Id of the destroyed context"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Issued when execution context is destroyed."]

module Execution_contexts_cleared = struct
  let name = "Runtime.executionContextsCleared"

  type params = unit [@@deriving show, eq]

  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Issued when all executionContexts were cleared in browser"]

module Inspect_requested = struct
  let name = "Runtime.inspectRequested"

  type params = {
    object_ : remote_object; [@key "object"]
    hints : Cdp_json.t; [@key "hints"]
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t option;
       [@key "executionContextId"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Identifier of the context where the call was made."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Issued when object should be inspected (for example, as a result of inspect() command line API\ncall)."]
