(* Generated by cdp-gen from Chrome DevTools Protocol r1680125. DO NOT EDIT. *)

include Cdp_dom_types
open Jsonkit.Primitives

module Collect_class_names_from_subtree = struct
  let name = "DOM.collectClassNamesFromSubtree"

  type params = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { class_names : string list [@key "classNames"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Copy_to = struct
  let name = "DOM.copyTo"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    target_node_id : Cdp_base.Dom.Node_id.t; [@key "targetNodeId"]
    insert_before_node_id : Cdp_base.Dom.Node_id.t option; [@key "insertBeforeNodeId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Describe_node = struct
  let name = "DOM.describeNode"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option; [@key "nodeId"] [@option] [@json.drop_default]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option; [@key "backendNodeId"] [@option] [@json.drop_default]
    object_id : Cdp_base.Runtime.Remote_object_id.t option; [@key "objectId"] [@option] [@json.drop_default]
    depth : int option; [@key "depth"] [@option] [@json.drop_default]
    pierce : bool option; [@key "pierce"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node : node [@key "node"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Scroll_into_view_if_needed = struct
  let name = "DOM.scrollIntoViewIfNeeded"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option; [@key "nodeId"] [@option] [@json.drop_default]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option; [@key "backendNodeId"] [@option] [@json.drop_default]
    object_id : Cdp_base.Runtime.Remote_object_id.t option; [@key "objectId"] [@option] [@json.drop_default]
    rect : rect option; [@key "rect"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Disable = struct
  let name = "DOM.disable"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Discard_search_results = struct
  let name = "DOM.discardSearchResults"

  type params = { search_id : string [@key "searchId"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Enable = struct
  let name = "DOM.enable"

  type include_whitespace =
    | None_ [@json.name "none"]
    | All [@json.name "all"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    include_whitespace : include_whitespace option; [@key "includeWhitespace"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Focus = struct
  let name = "DOM.focus"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option; [@key "nodeId"] [@option] [@json.drop_default]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option; [@key "backendNodeId"] [@option] [@json.drop_default]
    object_id : Cdp_base.Runtime.Remote_object_id.t option; [@key "objectId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_attributes = struct
  let name = "DOM.getAttributes"

  type params = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { attributes : string list [@key "attributes"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_box_model = struct
  let name = "DOM.getBoxModel"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option; [@key "nodeId"] [@option] [@json.drop_default]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option; [@key "backendNodeId"] [@option] [@json.drop_default]
    object_id : Cdp_base.Runtime.Remote_object_id.t option; [@key "objectId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { model : box_model [@key "model"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_content_quads = struct
  let name = "DOM.getContentQuads"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option; [@key "nodeId"] [@option] [@json.drop_default]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option; [@key "backendNodeId"] [@option] [@json.drop_default]
    object_id : Cdp_base.Runtime.Remote_object_id.t option; [@key "objectId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { quads : quad list [@key "quads"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_document = struct
  let name = "DOM.getDocument"

  type params = {
    depth : int option; [@key "depth"] [@option] [@json.drop_default]
    pierce : bool option; [@key "pierce"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { root : node [@key "root"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_flattened_document = struct
  let name = "DOM.getFlattenedDocument"

  type params = {
    depth : int option; [@key "depth"] [@option] [@json.drop_default]
    pierce : bool option; [@key "pierce"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { nodes : node list [@key "nodes"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Get_nodes_for_subtree_by_style = struct
  let name = "DOM.getNodesForSubtreeByStyle"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    computed_styles : css_computed_style_property list; [@key "computedStyles"]
    pierce : bool option; [@key "pierce"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_node_for_location = struct
  let name = "DOM.getNodeForLocation"

  type params = {
    x : int; [@key "x"]
    y : int; [@key "y"]
    include_user_agent_shadow_dom : bool option; [@key "includeUserAgentShadowDOM"] [@option] [@json.drop_default]
    ignore_pointer_events_none : bool option; [@key "ignorePointerEventsNone"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    backend_node_id : Cdp_base.Dom.Backend_node_id.t; [@key "backendNodeId"]
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    node_id : Cdp_base.Dom.Node_id.t option; [@key "nodeId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_outer_html = struct
  let name = "DOM.getOuterHTML"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option; [@key "nodeId"] [@option] [@json.drop_default]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option; [@key "backendNodeId"] [@option] [@json.drop_default]
    object_id : Cdp_base.Runtime.Remote_object_id.t option; [@key "objectId"] [@option] [@json.drop_default]
    include_shadow_dom : bool option; [@key "includeShadowDOM"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { outer_html : string [@key "outerHTML"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_relayout_boundary = struct
  let name = "DOM.getRelayoutBoundary"

  type params = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_search_results = struct
  let name = "DOM.getSearchResults"

  type params = {
    search_id : string; [@key "searchId"]
    from_index : int; [@key "fromIndex"]
    to_index : int; [@key "toIndex"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Hide_highlight = struct
  let name = "DOM.hideHighlight"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Highlight_node = struct
  let name = "DOM.highlightNode"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Highlight_rect = struct
  let name = "DOM.highlightRect"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Mark_undoable_state = struct
  let name = "DOM.markUndoableState"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Move_to = struct
  let name = "DOM.moveTo"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    target_node_id : Cdp_base.Dom.Node_id.t; [@key "targetNodeId"]
    insert_before_node_id : Cdp_base.Dom.Node_id.t option; [@key "insertBeforeNodeId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Perform_search = struct
  let name = "DOM.performSearch"

  type params = {
    query : string; [@key "query"]
    include_user_agent_shadow_dom : bool option; [@key "includeUserAgentShadowDOM"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    search_id : string; [@key "searchId"]
    result_count : int; [@key "resultCount"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Push_node_by_path_to_frontend = struct
  let name = "DOM.pushNodeByPathToFrontend"

  type params = { path : string [@key "path"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Push_nodes_by_backend_ids_to_frontend = struct
  let name = "DOM.pushNodesByBackendIdsToFrontend"

  type params = { backend_node_ids : Cdp_base.Dom.Backend_node_id.t list [@key "backendNodeIds"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Query_selector = struct
  let name = "DOM.querySelector"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    selector : string; [@key "selector"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Query_selector_all = struct
  let name = "DOM.querySelectorAll"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    selector : string; [@key "selector"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_top_layer_elements = struct
  let name = "DOM.getTopLayerElements"

  type result = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_element_by_relation = struct
  let name = "DOM.getElementByRelation"

  type relation =
    | PopoverTarget [@json.name "PopoverTarget"]
    | InterestTarget [@json.name "InterestTarget"]
    | CommandFor [@json.name "CommandFor"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    relation : relation; [@key "relation"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Redo = struct
  let name = "DOM.redo"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Remove_attribute = struct
  let name = "DOM.removeAttribute"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    name : string; [@key "name"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Remove_node = struct
  let name = "DOM.removeNode"

  type params = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Request_child_nodes = struct
  let name = "DOM.requestChildNodes"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    depth : int option; [@key "depth"] [@option] [@json.drop_default]
    pierce : bool option; [@key "pierce"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Request_node = struct
  let name = "DOM.requestNode"

  type params = { object_id : Cdp_base.Runtime.Remote_object_id.t [@key "objectId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Resolve_node = struct
  let name = "DOM.resolveNode"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option; [@key "nodeId"] [@option] [@json.drop_default]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option; [@key "backendNodeId"] [@option] [@json.drop_default]
    object_group : string option; [@key "objectGroup"] [@option] [@json.drop_default]
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t option;
       [@key "executionContextId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { object_ : Cdp_runtime_types.remote_object [@key "object"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_attribute_value = struct
  let name = "DOM.setAttributeValue"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    name : string; [@key "name"]
    value : string; [@key "value"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_attributes_as_text = struct
  let name = "DOM.setAttributesAsText"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    text : string; [@key "text"]
    name : string option; [@key "name"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_file_input_files = struct
  let name = "DOM.setFileInputFiles"

  type params = {
    files : string list; [@key "files"]
    node_id : Cdp_base.Dom.Node_id.t option; [@key "nodeId"] [@option] [@json.drop_default]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option; [@key "backendNodeId"] [@option] [@json.drop_default]
    object_id : Cdp_base.Runtime.Remote_object_id.t option; [@key "objectId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_node_stack_traces_enabled = struct
  let name = "DOM.setNodeStackTracesEnabled"

  type params = { enable : bool [@key "enable"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_node_stack_traces = struct
  let name = "DOM.getNodeStackTraces"

  type params = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { creation : Cdp_runtime_types.stack_trace option [@key "creation"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_file_info = struct
  let name = "DOM.getFileInfo"

  type params = { object_id : Cdp_base.Runtime.Remote_object_id.t [@key "objectId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { path : string [@key "path"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_detached_dom_nodes = struct
  let name = "DOM.getDetachedDomNodes"

  type result = { detached_nodes : detached_element_info list [@key "detachedNodes"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_inspected_node = struct
  let name = "DOM.setInspectedNode"

  type params = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_node_name = struct
  let name = "DOM.setNodeName"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    name : string; [@key "name"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_node_value = struct
  let name = "DOM.setNodeValue"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    value : string; [@key "value"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_outer_html = struct
  let name = "DOM.setOuterHTML"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    outer_html : string; [@key "outerHTML"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Undo = struct
  let name = "DOM.undo"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_frame_owner = struct
  let name = "DOM.getFrameOwner"

  type params = { frame_id : Cdp_base.Page.Frame_id.t [@key "frameId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    backend_node_id : Cdp_base.Dom.Backend_node_id.t; [@key "backendNodeId"]
    node_id : Cdp_base.Dom.Node_id.t option; [@key "nodeId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_container_for_node = struct
  let name = "DOM.getContainerForNode"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    container_name : string option; [@key "containerName"] [@option] [@json.drop_default]
    physical_axes : physical_axes option; [@key "physicalAxes"] [@option] [@json.drop_default]
    logical_axes : logical_axes option; [@key "logicalAxes"] [@option] [@json.drop_default]
    queries_scroll_state : bool option; [@key "queriesScrollState"] [@option] [@json.drop_default]
    queries_anchored : bool option; [@key "queriesAnchored"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t option [@key "nodeId"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_querying_descendants_for_container = struct
  let name = "DOM.getQueryingDescendantsForContainer"

  type params = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_anchor_element = struct
  let name = "DOM.getAnchorElement"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    anchor_specifier : string option; [@key "anchorSpecifier"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Force_show_popover = struct
  let name = "DOM.forceShowPopover"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    enable : bool; [@key "enable"]
    invoker_node_id : Cdp_base.Dom.Backend_node_id.t option; [@key "invokerNodeId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Force_show_interest = struct
  let name = "DOM.forceShowInterest"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    enable : bool; [@key "enable"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Attribute_modified = struct
  let name = "DOM.attributeModified"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    name : string; [@key "name"]
    value : string; [@key "value"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Adopted_style_sheets_modified = struct
  let name = "DOM.adoptedStyleSheetsModified"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    adopted_style_sheets : Cdp_base.Dom.Style_sheet_id.t list; [@key "adoptedStyleSheets"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Attribute_removed = struct
  let name = "DOM.attributeRemoved"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    name : string; [@key "name"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Character_data_modified = struct
  let name = "DOM.characterDataModified"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    character_data : string; [@key "characterData"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Child_node_count_updated = struct
  let name = "DOM.childNodeCountUpdated"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    child_node_count : int; [@key "childNodeCount"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Child_node_inserted = struct
  let name = "DOM.childNodeInserted"

  type params = {
    parent_node_id : Cdp_base.Dom.Node_id.t; [@key "parentNodeId"]
    previous_node_id : Cdp_base.Dom.Node_id.t; [@key "previousNodeId"]
    node : node; [@key "node"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Child_node_removed = struct
  let name = "DOM.childNodeRemoved"

  type params = {
    parent_node_id : Cdp_base.Dom.Node_id.t; [@key "parentNodeId"]
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Distributed_nodes_updated = struct
  let name = "DOM.distributedNodesUpdated"

  type params = {
    insertion_point_id : Cdp_base.Dom.Node_id.t; [@key "insertionPointId"]
    distributed_nodes : backend_node list; [@key "distributedNodes"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Document_updated = struct
  let name = "DOM.documentUpdated"

  type params = unit [@@deriving show, eq]

  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Inline_style_invalidated = struct
  let name = "DOM.inlineStyleInvalidated"

  type params = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Pseudo_element_added = struct
  let name = "DOM.pseudoElementAdded"

  type params = {
    parent_id : Cdp_base.Dom.Node_id.t; [@key "parentId"]
    pseudo_element : node; [@key "pseudoElement"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Top_layer_elements_updated = struct
  let name = "DOM.topLayerElementsUpdated"

  type params = unit [@@deriving show, eq]

  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Scrollable_flag_updated = struct
  let name = "DOM.scrollableFlagUpdated"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    is_scrollable : bool; [@key "isScrollable"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Ad_related_state_updated = struct
  let name = "DOM.adRelatedStateUpdated"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    ad_provenance : Cdp_network_types.ad_provenance option; [@key "adProvenance"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Affected_by_starting_styles_flag_updated = struct
  let name = "DOM.affectedByStartingStylesFlagUpdated"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    affected_by_starting_styles : bool; [@key "affectedByStartingStyles"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Pseudo_element_removed = struct
  let name = "DOM.pseudoElementRemoved"

  type params = {
    parent_id : Cdp_base.Dom.Node_id.t; [@key "parentId"]
    pseudo_element_id : Cdp_base.Dom.Node_id.t; [@key "pseudoElementId"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_child_nodes = struct
  let name = "DOM.setChildNodes"

  type params = {
    parent_id : Cdp_base.Dom.Node_id.t; [@key "parentId"]
    nodes : node list; [@key "nodes"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Shadow_root_popped = struct
  let name = "DOM.shadowRootPopped"

  type params = {
    host_id : Cdp_base.Dom.Node_id.t; [@key "hostId"]
    root_id : Cdp_base.Dom.Node_id.t; [@key "rootId"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Shadow_root_pushed = struct
  let name = "DOM.shadowRootPushed"

  type params = {
    host_id : Cdp_base.Dom.Node_id.t; [@key "hostId"]
    root : node; [@key "root"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]
