(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)

open Jsonkit.Primitives

module Frame_id = Cdp_base.Page.Frame_id
module Script_identifier = Cdp_base.Page.Script_identifier

type ad_frame_type =
  | None_ [@json.name "none"]
  | Child [@json.name "child"]
  | Root [@json.name "root"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and ad_frame_explanation =
  | ParentIsAd [@json.name "ParentIsAd"]
  | CreatedByAdScript [@json.name "CreatedByAdScript"]
  | MatchedBlockingRule [@json.name "MatchedBlockingRule"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and ad_frame_status = {
  ad_frame_type : ad_frame_type; [@key "adFrameType"]
  explanations : ad_frame_explanation list option; [@key "explanations"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and secure_context_type =
  | Secure [@json.name "Secure"]
  | SecureLocalhost [@json.name "SecureLocalhost"]
  | InsecureScheme [@json.name "InsecureScheme"]
  | InsecureAncestor [@json.name "InsecureAncestor"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and cross_origin_isolated_context_type =
  | Isolated [@json.name "Isolated"]
  | NotIsolated [@json.name "NotIsolated"]
  | NotIsolatedFeatureDisabled [@json.name "NotIsolatedFeatureDisabled"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and gated_api_features =
  | SharedArrayBuffers [@json.name "SharedArrayBuffers"]
  | SharedArrayBuffersTransferAllowed [@json.name "SharedArrayBuffersTransferAllowed"]
  | PerformanceMeasureMemory [@json.name "PerformanceMeasureMemory"]
  | PerformanceProfile [@json.name "PerformanceProfile"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and permissions_policy_feature =
  | Accelerometer [@json.name "accelerometer"]
  | All_screens_capture [@json.name "all-screens-capture"]
  | Ambient_light_sensor [@json.name "ambient-light-sensor"]
  | Aria_notify [@json.name "aria-notify"]
  | Autofill [@json.name "autofill"]
  | Autoplay [@json.name "autoplay"]
  | Bluetooth [@json.name "bluetooth"]
  | Browsing_topics [@json.name "browsing-topics"]
  | Camera [@json.name "camera"]
  | Captured_surface_control [@json.name "captured-surface-control"]
  | Ch_dpr [@json.name "ch-dpr"]
  | Ch_device_memory [@json.name "ch-device-memory"]
  | Ch_downlink [@json.name "ch-downlink"]
  | Ch_ect [@json.name "ch-ect"]
  | Ch_prefers_color_scheme [@json.name "ch-prefers-color-scheme"]
  | Ch_prefers_reduced_motion [@json.name "ch-prefers-reduced-motion"]
  | Ch_prefers_reduced_transparency [@json.name "ch-prefers-reduced-transparency"]
  | Ch_rtt [@json.name "ch-rtt"]
  | Ch_save_data [@json.name "ch-save-data"]
  | Ch_ua [@json.name "ch-ua"]
  | Ch_ua_arch [@json.name "ch-ua-arch"]
  | Ch_ua_bitness [@json.name "ch-ua-bitness"]
  | Ch_ua_high_entropy_values [@json.name "ch-ua-high-entropy-values"]
  | Ch_ua_platform [@json.name "ch-ua-platform"]
  | Ch_ua_model [@json.name "ch-ua-model"]
  | Ch_ua_mobile [@json.name "ch-ua-mobile"]
  | Ch_ua_form_factors [@json.name "ch-ua-form-factors"]
  | Ch_ua_full_version [@json.name "ch-ua-full-version"]
  | Ch_ua_full_version_list [@json.name "ch-ua-full-version-list"]
  | Ch_ua_platform_version [@json.name "ch-ua-platform-version"]
  | Ch_ua_wow64 [@json.name "ch-ua-wow64"]
  | Ch_viewport_height [@json.name "ch-viewport-height"]
  | Ch_viewport_width [@json.name "ch-viewport-width"]
  | Ch_width [@json.name "ch-width"]
  | Clipboard_read [@json.name "clipboard-read"]
  | Clipboard_write [@json.name "clipboard-write"]
  | Compute_pressure [@json.name "compute-pressure"]
  | Controlled_frame [@json.name "controlled-frame"]
  | Cross_origin_isolated [@json.name "cross-origin-isolated"]
  | Deferred_fetch [@json.name "deferred-fetch"]
  | Deferred_fetch_minimal [@json.name "deferred-fetch-minimal"]
  | Device_attributes [@json.name "device-attributes"]
  | Digital_credentials_create [@json.name "digital-credentials-create"]
  | Digital_credentials_get [@json.name "digital-credentials-get"]
  | Direct_sockets [@json.name "direct-sockets"]
  | Direct_sockets_multicast [@json.name "direct-sockets-multicast"]
  | Display_capture [@json.name "display-capture"]
  | Document_domain [@json.name "document-domain"]
  | Encrypted_media [@json.name "encrypted-media"]
  | Execution_while_out_of_viewport [@json.name "execution-while-out-of-viewport"]
  | Execution_while_not_rendered [@json.name "execution-while-not-rendered"]
  | Focus_without_user_activation [@json.name "focus-without-user-activation"]
  | Fullscreen [@json.name "fullscreen"]
  | Frobulate [@json.name "frobulate"]
  | Gamepad [@json.name "gamepad"]
  | Geolocation [@json.name "geolocation"]
  | Gyroscope [@json.name "gyroscope"]
  | Haptics [@json.name "haptics"]
  | Hid [@json.name "hid"]
  | Identity_credentials_get [@json.name "identity-credentials-get"]
  | Idle_detection [@json.name "idle-detection"]
  | Interest_cohort [@json.name "interest-cohort"]
  | Keyboard_map [@json.name "keyboard-map"]
  | Language_detector [@json.name "language-detector"]
  | Language_model [@json.name "language-model"]
  | Local_fonts [@json.name "local-fonts"]
  | Local_network [@json.name "local-network"]
  | Local_network_access [@json.name "local-network-access"]
  | Loopback_network [@json.name "loopback-network"]
  | Magnetometer [@json.name "magnetometer"]
  | Manual_text [@json.name "manual-text"]
  | Media_playback_while_not_visible [@json.name "media-playback-while-not-visible"]
  | Microphone [@json.name "microphone"]
  | Midi [@json.name "midi"]
  | On_device_speech_recognition [@json.name "on-device-speech-recognition"]
  | Otp_credentials [@json.name "otp-credentials"]
  | Payment [@json.name "payment"]
  | Picture_in_picture [@json.name "picture-in-picture"]
  | Private_state_token_issuance [@json.name "private-state-token-issuance"]
  | Private_state_token_redemption [@json.name "private-state-token-redemption"]
  | Publickey_credentials_create [@json.name "publickey-credentials-create"]
  | Publickey_credentials_get [@json.name "publickey-credentials-get"]
  | Rewriter [@json.name "rewriter"]
  | Screen_wake_lock [@json.name "screen-wake-lock"]
  | Serial [@json.name "serial"]
  | Shared_storage [@json.name "shared-storage"]
  | Shared_storage_select_url [@json.name "shared-storage-select-url"]
  | Smart_card [@json.name "smart-card"]
  | Speaker_selection [@json.name "speaker-selection"]
  | Storage_access [@json.name "storage-access"]
  | Sub_apps [@json.name "sub-apps"]
  | Summarizer [@json.name "summarizer"]
  | Sync_xhr [@json.name "sync-xhr"]
  | Tools [@json.name "tools"]
  | Translator [@json.name "translator"]
  | Unload [@json.name "unload"]
  | Usb [@json.name "usb"]
  | Usb_unrestricted [@json.name "usb-unrestricted"]
  | Vertical_scroll [@json.name "vertical-scroll"]
  | Web_app_installation [@json.name "web-app-installation"]
  | Webnn [@json.name "webnn"]
  | Web_printing [@json.name "web-printing"]
  | Web_share [@json.name "web-share"]
  | Window_management [@json.name "window-management"]
  | Writer [@json.name "writer"]
  | Xr_spatial_tracking [@json.name "xr-spatial-tracking"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and permissions_policy_block_reason =
  | Header [@json.name "Header"]
  | IframeAttribute [@json.name "IframeAttribute"]
  | InFencedFrameTree [@json.name "InFencedFrameTree"]
  | InIsolatedApp [@json.name "InIsolatedApp"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and permissions_policy_block_locator = {
  frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
  block_reason : permissions_policy_block_reason; [@key "blockReason"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and permissions_policy_feature_state = {
  feature : permissions_policy_feature; [@key "feature"]
  allowed : bool; [@key "allowed"]
  locator : permissions_policy_block_locator option; [@key "locator"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and origin_trial_token_status =
  | Success [@json.name "Success"]
  | NotSupported [@json.name "NotSupported"]
  | Insecure [@json.name "Insecure"]
  | Expired [@json.name "Expired"]
  | WrongOrigin [@json.name "WrongOrigin"]
  | InvalidSignature [@json.name "InvalidSignature"]
  | Malformed [@json.name "Malformed"]
  | WrongVersion [@json.name "WrongVersion"]
  | FeatureDisabled [@json.name "FeatureDisabled"]
  | TokenDisabled [@json.name "TokenDisabled"]
  | FeatureDisabledForUser [@json.name "FeatureDisabledForUser"]
  | UnknownTrial [@json.name "UnknownTrial"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and origin_trial_status =
  | Enabled [@json.name "Enabled"]
  | ValidTokenNotProvided [@json.name "ValidTokenNotProvided"]
  | OSNotSupported [@json.name "OSNotSupported"]
  | TrialNotAllowed [@json.name "TrialNotAllowed"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and origin_trial_usage_restriction =
  | None_ [@json.name "None"]
  | Subset [@json.name "Subset"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and origin_trial_token = {
  origin : string; [@key "origin"]
  match_sub_domains : bool; [@key "matchSubDomains"]
  trial_name : string; [@key "trialName"]
  expiry_time : Cdp_base.Network.Time_since_epoch.t; [@key "expiryTime"]
  is_third_party : bool; [@key "isThirdParty"]
  usage_restriction : origin_trial_usage_restriction; [@key "usageRestriction"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and origin_trial_token_with_status = {
  raw_token_text : string; [@key "rawTokenText"]
  parsed_token : origin_trial_token option; [@key "parsedToken"] [@option] [@json.drop_default]
  status : origin_trial_token_status; [@key "status"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and origin_trial = {
  trial_name : string; [@key "trialName"]
  status : origin_trial_status; [@key "status"]
  tokens_with_status : origin_trial_token_with_status list; [@key "tokensWithStatus"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and security_origin_details = { is_localhost : bool [@key "isLocalhost"] }
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and frame = {
  id : Cdp_base.Page.Frame_id.t; [@key "id"]
  parent_id : Cdp_base.Page.Frame_id.t option; [@key "parentId"] [@option] [@json.drop_default]
  loader_id : Cdp_base.Network.Loader_id.t; [@key "loaderId"]
  name : string option; [@key "name"] [@option] [@json.drop_default]
  url : string; [@key "url"]
  url_fragment : string option;
     [@key "urlFragment"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  domain_and_registry : string;
     [@key "domainAndRegistry"] [@alert experimental "experimental in CDP, may change with Chrome"]
  security_origin : string; [@key "securityOrigin"]
  security_origin_details : security_origin_details option;
     [@key "securityOriginDetails"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  mime_type : string; [@key "mimeType"]
  unreachable_url : string option;
     [@key "unreachableUrl"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  ad_frame_status : ad_frame_status option;
     [@key "adFrameStatus"]
     [@option]
     [@json.drop_default]
     [@alert experimental "experimental in CDP, may change with Chrome"]
  secure_context_type : secure_context_type;
     [@key "secureContextType"] [@alert experimental "experimental in CDP, may change with Chrome"]
  cross_origin_isolated_context_type : cross_origin_isolated_context_type;
     [@key "crossOriginIsolatedContextType"] [@alert experimental "experimental in CDP, may change with Chrome"]
  gated_api_features : gated_api_features list;
     [@key "gatedAPIFeatures"] [@alert experimental "experimental in CDP, may change with Chrome"]
}
[@@allow_extra_fields]

and frame_resource = {
  url : string; [@key "url"]
  type_ : Cdp_network_types.resource_type; [@key "type"]
  mime_type : string; [@key "mimeType"]
  last_modified : Cdp_base.Network.Time_since_epoch.t option; [@key "lastModified"] [@option] [@json.drop_default]
  content_size : float option; [@key "contentSize"] [@option] [@json.drop_default]
  failed : bool option; [@key "failed"] [@option] [@json.drop_default]
  canceled : bool option; [@key "canceled"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and frame_resource_tree = {
  frame : frame; [@key "frame"]
  child_frames : frame_resource_tree list option; [@key "childFrames"] [@option] [@json.drop_default]
  resources : frame_resource list; [@key "resources"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and frame_tree = {
  frame : frame; [@key "frame"]
  child_frames : frame_tree list option; [@key "childFrames"] [@option] [@json.drop_default]
}
[@@allow_extra_fields]

and transition_type =
  | Link [@json.name "link"]
  | Typed [@json.name "typed"]
  | Address_bar [@json.name "address_bar"]
  | Auto_bookmark [@json.name "auto_bookmark"]
  | Auto_subframe [@json.name "auto_subframe"]
  | Manual_subframe [@json.name "manual_subframe"]
  | Generated [@json.name "generated"]
  | Auto_toplevel [@json.name "auto_toplevel"]
  | Form_submit [@json.name "form_submit"]
  | Reload [@json.name "reload"]
  | Keyword [@json.name "keyword"]
  | Keyword_generated [@json.name "keyword_generated"]
  | Other_ [@json.name "other"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants]

and navigation_entry = {
  id : int; [@key "id"]
  url : string; [@key "url"]
  user_typed_url : string; [@key "userTypedURL"]
  title : string; [@key "title"]
  transition_type : transition_type; [@key "transitionType"]
}
[@@allow_extra_fields]

and screencast_frame_metadata = {
  offset_top : float; [@key "offsetTop"]
  page_scale_factor : float; [@key "pageScaleFactor"]
  device_width : float; [@key "deviceWidth"]
  device_height : float; [@key "deviceHeight"]
  scroll_offset_x : float; [@key "scrollOffsetX"]
  scroll_offset_y : float; [@key "scrollOffsetY"]
  timestamp : Cdp_base.Network.Time_since_epoch.t option; [@key "timestamp"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and dialog_type =
  | Alert [@json.name "alert"]
  | Confirm [@json.name "confirm"]
  | Prompt [@json.name "prompt"]
  | Beforeunload [@json.name "beforeunload"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants]

and app_manifest_error = {
  message : string; [@key "message"]
  critical : int; [@key "critical"]
  line : int; [@key "line"]
  column : int; [@key "column"]
}
[@@allow_extra_fields]

and app_manifest_parsed_properties = { scope : string [@key "scope"] }
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and layout_viewport = {
  page_x : int; [@key "pageX"]
  page_y : int; [@key "pageY"]
  client_width : int; [@key "clientWidth"]
  client_height : int; [@key "clientHeight"]
}
[@@allow_extra_fields]

and visual_viewport = {
  offset_x : float; [@key "offsetX"]
  offset_y : float; [@key "offsetY"]
  page_x : float; [@key "pageX"]
  page_y : float; [@key "pageY"]
  client_width : float; [@key "clientWidth"]
  client_height : float; [@key "clientHeight"]
  scale : float; [@key "scale"]
  zoom : float option; [@key "zoom"] [@option] [@json.drop_default]
}
[@@allow_extra_fields]

and viewport = {
  x : float; [@key "x"]
  y : float; [@key "y"]
  width : float; [@key "width"]
  height : float; [@key "height"]
  scale : float; [@key "scale"]
}
[@@allow_extra_fields]

and font_families = {
  standard : string option; [@key "standard"] [@option] [@json.drop_default]
  fixed : string option; [@key "fixed"] [@option] [@json.drop_default]
  serif : string option; [@key "serif"] [@option] [@json.drop_default]
  sans_serif : string option; [@key "sansSerif"] [@option] [@json.drop_default]
  cursive : string option; [@key "cursive"] [@option] [@json.drop_default]
  fantasy : string option; [@key "fantasy"] [@option] [@json.drop_default]
  math : string option; [@key "math"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and script_font_families = {
  script : string; [@key "script"]
  font_families : font_families; [@key "fontFamilies"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and font_sizes = {
  standard : int option; [@key "standard"] [@option] [@json.drop_default]
  fixed : int option; [@key "fixed"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and client_navigation_reason =
  | AnchorClick [@json.name "anchorClick"]
  | FormSubmissionGet [@json.name "formSubmissionGet"]
  | FormSubmissionPost [@json.name "formSubmissionPost"]
  | HttpHeaderRefresh [@json.name "httpHeaderRefresh"]
  | InitialFrameNavigation [@json.name "initialFrameNavigation"]
  | MetaTagRefresh [@json.name "metaTagRefresh"]
  | Other_ [@json.name "other"]
  | PageBlockInterstitial [@json.name "pageBlockInterstitial"]
  | Reload [@json.name "reload"]
  | ScriptInitiated [@json.name "scriptInitiated"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and client_navigation_disposition =
  | CurrentTab [@json.name "currentTab"]
  | NewTab [@json.name "newTab"]
  | NewWindow [@json.name "newWindow"]
  | Download [@json.name "download"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and installability_error_argument = {
  name : string; [@key "name"]
  value : string; [@key "value"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and installability_error = {
  error_id : string; [@key "errorId"]
  error_arguments : installability_error_argument list; [@key "errorArguments"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and referrer_policy =
  | NoReferrer [@json.name "noReferrer"]
  | NoReferrerWhenDowngrade [@json.name "noReferrerWhenDowngrade"]
  | Origin [@json.name "origin"]
  | OriginWhenCrossOrigin [@json.name "originWhenCrossOrigin"]
  | SameOrigin [@json.name "sameOrigin"]
  | StrictOrigin [@json.name "strictOrigin"]
  | StrictOriginWhenCrossOrigin [@json.name "strictOriginWhenCrossOrigin"]
  | UnsafeUrl [@json.name "unsafeUrl"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and compilation_cache_params = {
  url : string; [@key "url"]
  eager : bool option; [@key "eager"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and file_filter = {
  name : string option; [@key "name"] [@option] [@json.drop_default]
  accepts : string list option; [@key "accepts"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and file_handler = {
  action : string; [@key "action"]
  name : string; [@key "name"]
  accepts : file_filter list option; [@key "accepts"] [@option] [@json.drop_default]
  launch_type : string; [@key "launchType"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and image_resource = {
  url : string; [@key "url"]
  sizes : string option; [@key "sizes"] [@option] [@json.drop_default]
  type_ : string option; [@key "type"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and launch_handler = { client_mode : string [@key "clientMode"] }
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and protocol_handler = {
  protocol : string; [@key "protocol"]
  url : string; [@key "url"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and related_application = {
  id : string option; [@key "id"] [@option] [@json.drop_default]
  url : string; [@key "url"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and scope_extension = {
  origin : string; [@key "origin"]
  has_origin_wildcard : bool; [@key "hasOriginWildcard"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and screenshot = {
  image : image_resource; [@key "image"]
  form_factor : string; [@key "formFactor"]
  label : string option; [@key "label"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and share_target = {
  action : string; [@key "action"]
  method_ : string; [@key "method"]
  enctype : string; [@key "enctype"]
  title : string option; [@key "title"] [@option] [@json.drop_default]
  text : string option; [@key "text"] [@option] [@json.drop_default]
  url : string option; [@key "url"] [@option] [@json.drop_default]
  files : file_filter list option; [@key "files"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and shortcut = {
  name : string; [@key "name"]
  url : string; [@key "url"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and web_app_manifest = {
  background_color : string option; [@key "backgroundColor"] [@option] [@json.drop_default]
  description : string option; [@key "description"] [@option] [@json.drop_default]
  dir : string option; [@key "dir"] [@option] [@json.drop_default]
  display : string option; [@key "display"] [@option] [@json.drop_default]
  display_overrides : string list option; [@key "displayOverrides"] [@option] [@json.drop_default]
  file_handlers : file_handler list option; [@key "fileHandlers"] [@option] [@json.drop_default]
  icons : image_resource list option; [@key "icons"] [@option] [@json.drop_default]
  id : string option; [@key "id"] [@option] [@json.drop_default]
  lang : string option; [@key "lang"] [@option] [@json.drop_default]
  launch_handler : launch_handler option; [@key "launchHandler"] [@option] [@json.drop_default]
  name : string option; [@key "name"] [@option] [@json.drop_default]
  orientation : string option; [@key "orientation"] [@option] [@json.drop_default]
  prefer_related_applications : bool option; [@key "preferRelatedApplications"] [@option] [@json.drop_default]
  protocol_handlers : protocol_handler list option; [@key "protocolHandlers"] [@option] [@json.drop_default]
  related_applications : related_application list option; [@key "relatedApplications"] [@option] [@json.drop_default]
  scope : string option; [@key "scope"] [@option] [@json.drop_default]
  scope_extensions : scope_extension list option; [@key "scopeExtensions"] [@option] [@json.drop_default]
  screenshots : screenshot list option; [@key "screenshots"] [@option] [@json.drop_default]
  share_target : share_target option; [@key "shareTarget"] [@option] [@json.drop_default]
  short_name : string option; [@key "shortName"] [@option] [@json.drop_default]
  shortcuts : shortcut list option; [@key "shortcuts"] [@option] [@json.drop_default]
  start_url : string option; [@key "startUrl"] [@option] [@json.drop_default]
  theme_color : string option; [@key "themeColor"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and navigation_type =
  | Navigation [@json.name "Navigation"]
  | BackForwardCacheRestore [@json.name "BackForwardCacheRestore"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and back_forward_cache_not_restored_reason =
  | NotPrimaryMainFrame [@json.name "NotPrimaryMainFrame"]
  | BackForwardCacheDisabled [@json.name "BackForwardCacheDisabled"]
  | RelatedActiveContentsExist [@json.name "RelatedActiveContentsExist"]
  | HTTPStatusNotOK [@json.name "HTTPStatusNotOK"]
  | SchemeNotHTTPOrHTTPS [@json.name "SchemeNotHTTPOrHTTPS"]
  | Loading [@json.name "Loading"]
  | WasGrantedMediaAccess [@json.name "WasGrantedMediaAccess"]
  | DisableForRenderFrameHostCalled [@json.name "DisableForRenderFrameHostCalled"]
  | DomainNotAllowed [@json.name "DomainNotAllowed"]
  | HTTPMethodNotGET [@json.name "HTTPMethodNotGET"]
  | SubframeIsNavigating [@json.name "SubframeIsNavigating"]
  | Timeout [@json.name "Timeout"]
  | CacheLimit [@json.name "CacheLimit"]
  | JavaScriptExecution [@json.name "JavaScriptExecution"]
  | RendererProcessKilled [@json.name "RendererProcessKilled"]
  | RendererProcessCrashed [@json.name "RendererProcessCrashed"]
  | SchedulerTrackedFeatureUsed [@json.name "SchedulerTrackedFeatureUsed"]
  | ConflictingBrowsingInstance [@json.name "ConflictingBrowsingInstance"]
  | CacheFlushed [@json.name "CacheFlushed"]
  | ServiceWorkerVersionActivation [@json.name "ServiceWorkerVersionActivation"]
  | SessionRestored [@json.name "SessionRestored"]
  | ServiceWorkerPostMessage [@json.name "ServiceWorkerPostMessage"]
  | EnteredBackForwardCacheBeforeServiceWorkerHostAdded
    [@json.name "EnteredBackForwardCacheBeforeServiceWorkerHostAdded"]
  | RenderFrameHostReused_SameSite [@json.name "RenderFrameHostReused_SameSite"]
  | RenderFrameHostReused_CrossSite [@json.name "RenderFrameHostReused_CrossSite"]
  | ServiceWorkerClaim [@json.name "ServiceWorkerClaim"]
  | IgnoreEventAndEvict [@json.name "IgnoreEventAndEvict"]
  | HaveInnerContents [@json.name "HaveInnerContents"]
  | TimeoutPuttingInCache [@json.name "TimeoutPuttingInCache"]
  | BackForwardCacheDisabledByLowMemory [@json.name "BackForwardCacheDisabledByLowMemory"]
  | BackForwardCacheDisabledByCommandLine [@json.name "BackForwardCacheDisabledByCommandLine"]
  | NetworkRequestDatapipeDrainedAsBytesConsumer [@json.name "NetworkRequestDatapipeDrainedAsBytesConsumer"]
  | NetworkRequestRedirected [@json.name "NetworkRequestRedirected"]
  | NetworkRequestTimeout [@json.name "NetworkRequestTimeout"]
  | NetworkExceedsBufferLimit [@json.name "NetworkExceedsBufferLimit"]
  | NavigationCancelledWhileRestoring [@json.name "NavigationCancelledWhileRestoring"]
  | NotMostRecentNavigationEntry [@json.name "NotMostRecentNavigationEntry"]
  | BackForwardCacheDisabledForPrerender [@json.name "BackForwardCacheDisabledForPrerender"]
  | UserAgentOverrideDiffers [@json.name "UserAgentOverrideDiffers"]
  | ForegroundCacheLimit [@json.name "ForegroundCacheLimit"]
  | ForwardCacheDisabled [@json.name "ForwardCacheDisabled"]
  | BrowsingInstanceNotSwapped [@json.name "BrowsingInstanceNotSwapped"]
  | BackForwardCacheDisabledForDelegate [@json.name "BackForwardCacheDisabledForDelegate"]
  | UnloadHandlerExistsInMainFrame [@json.name "UnloadHandlerExistsInMainFrame"]
  | UnloadHandlerExistsInSubFrame [@json.name "UnloadHandlerExistsInSubFrame"]
  | ServiceWorkerUnregistration [@json.name "ServiceWorkerUnregistration"]
  | CacheControlNoStore [@json.name "CacheControlNoStore"]
  | CacheControlNoStoreCookieModified [@json.name "CacheControlNoStoreCookieModified"]
  | CacheControlNoStoreHTTPOnlyCookieModified [@json.name "CacheControlNoStoreHTTPOnlyCookieModified"]
  | NoResponseHead [@json.name "NoResponseHead"]
  | Unknown [@json.name "Unknown"]
  | ActivationNavigationsDisallowedForBug1234857 [@json.name "ActivationNavigationsDisallowedForBug1234857"]
  | ErrorDocument [@json.name "ErrorDocument"]
  | FencedFramesEmbedder [@json.name "FencedFramesEmbedder"]
  | CookieDisabled [@json.name "CookieDisabled"]
  | HTTPAuthRequired [@json.name "HTTPAuthRequired"]
  | CookieFlushed [@json.name "CookieFlushed"]
  | BroadcastChannelOnMessage [@json.name "BroadcastChannelOnMessage"]
  | WebViewSettingsChanged [@json.name "WebViewSettingsChanged"]
  | WebViewJavaScriptObjectChanged [@json.name "WebViewJavaScriptObjectChanged"]
  | WebViewMessageListenerInjected [@json.name "WebViewMessageListenerInjected"]
  | WebViewSafeBrowsingAllowlistChanged [@json.name "WebViewSafeBrowsingAllowlistChanged"]
  | WebViewDocumentStartJavascriptChanged [@json.name "WebViewDocumentStartJavascriptChanged"]
  | WebSocket [@json.name "WebSocket"]
  | WebTransport [@json.name "WebTransport"]
  | WebRTC [@json.name "WebRTC"]
  | MainResourceHasCacheControlNoStore [@json.name "MainResourceHasCacheControlNoStore"]
  | MainResourceHasCacheControlNoCache [@json.name "MainResourceHasCacheControlNoCache"]
  | SubresourceHasCacheControlNoStore [@json.name "SubresourceHasCacheControlNoStore"]
  | SubresourceHasCacheControlNoCache [@json.name "SubresourceHasCacheControlNoCache"]
  | ContainsPlugins [@json.name "ContainsPlugins"]
  | DocumentLoaded [@json.name "DocumentLoaded"]
  | OutstandingNetworkRequestOthers [@json.name "OutstandingNetworkRequestOthers"]
  | RequestedMIDIPermission [@json.name "RequestedMIDIPermission"]
  | RequestedAudioCapturePermission [@json.name "RequestedAudioCapturePermission"]
  | RequestedVideoCapturePermission [@json.name "RequestedVideoCapturePermission"]
  | RequestedBackForwardCacheBlockedSensors [@json.name "RequestedBackForwardCacheBlockedSensors"]
  | RequestedBackgroundWorkPermission [@json.name "RequestedBackgroundWorkPermission"]
  | BroadcastChannel [@json.name "BroadcastChannel"]
  | WebXR [@json.name "WebXR"]
  | SharedWorker [@json.name "SharedWorker"]
  | SharedWorkerMessage [@json.name "SharedWorkerMessage"]
  | SharedWorkerWithNoActiveClient [@json.name "SharedWorkerWithNoActiveClient"]
  | WebLocks [@json.name "WebLocks"]
  | WebLocksContention [@json.name "WebLocksContention"]
  | WebHID [@json.name "WebHID"]
  | WebBluetooth [@json.name "WebBluetooth"]
  | WebShare [@json.name "WebShare"]
  | RequestedStorageAccessGrant [@json.name "RequestedStorageAccessGrant"]
  | WebNfc [@json.name "WebNfc"]
  | OutstandingNetworkRequestFetch [@json.name "OutstandingNetworkRequestFetch"]
  | OutstandingNetworkRequestXHR [@json.name "OutstandingNetworkRequestXHR"]
  | AppBanner [@json.name "AppBanner"]
  | Printing [@json.name "Printing"]
  | WebDatabase [@json.name "WebDatabase"]
  | PictureInPicture [@json.name "PictureInPicture"]
  | SpeechRecognizer [@json.name "SpeechRecognizer"]
  | IdleManager [@json.name "IdleManager"]
  | PaymentManager [@json.name "PaymentManager"]
  | SpeechSynthesis [@json.name "SpeechSynthesis"]
  | KeyboardLock [@json.name "KeyboardLock"]
  | WebOTPService [@json.name "WebOTPService"]
  | OutstandingNetworkRequestDirectSocket [@json.name "OutstandingNetworkRequestDirectSocket"]
  | InjectedJavascript [@json.name "InjectedJavascript"]
  | InjectedStyleSheet [@json.name "InjectedStyleSheet"]
  | KeepaliveRequest [@json.name "KeepaliveRequest"]
  | IndexedDBEvent [@json.name "IndexedDBEvent"]
  | Dummy [@json.name "Dummy"]
  | JsNetworkRequestReceivedCacheControlNoStoreResource
    [@json.name "JsNetworkRequestReceivedCacheControlNoStoreResource"]
  | WebRTCUsedWithCCNS [@json.name "WebRTCUsedWithCCNS"]
  | WebTransportUsedWithCCNS [@json.name "WebTransportUsedWithCCNS"]
  | WebSocketUsedWithCCNS [@json.name "WebSocketUsedWithCCNS"]
  | SmartCard [@json.name "SmartCard"]
  | LiveMediaStreamTrack [@json.name "LiveMediaStreamTrack"]
  | UnloadHandler [@json.name "UnloadHandler"]
  | ParserAborted [@json.name "ParserAborted"]
  | ContentSecurityHandler [@json.name "ContentSecurityHandler"]
  | ContentWebAuthenticationAPI [@json.name "ContentWebAuthenticationAPI"]
  | ContentFileChooser [@json.name "ContentFileChooser"]
  | ContentSerial [@json.name "ContentSerial"]
  | ContentFileSystemAccess [@json.name "ContentFileSystemAccess"]
  | ContentMediaDevicesDispatcherHost [@json.name "ContentMediaDevicesDispatcherHost"]
  | ContentWebBluetooth [@json.name "ContentWebBluetooth"]
  | ContentWebUSB [@json.name "ContentWebUSB"]
  | ContentMediaSessionService [@json.name "ContentMediaSessionService"]
  | ContentScreenReader [@json.name "ContentScreenReader"]
  | ContentDiscarded [@json.name "ContentDiscarded"]
  | EmbedderPopupBlockerTabHelper [@json.name "EmbedderPopupBlockerTabHelper"]
  | EmbedderSafeBrowsingTriggeredPopupBlocker [@json.name "EmbedderSafeBrowsingTriggeredPopupBlocker"]
  | EmbedderSafeBrowsingThreatDetails [@json.name "EmbedderSafeBrowsingThreatDetails"]
  | EmbedderAppBannerManager [@json.name "EmbedderAppBannerManager"]
  | EmbedderDomDistillerViewerSource [@json.name "EmbedderDomDistillerViewerSource"]
  | EmbedderDomDistillerSelfDeletingRequestDelegate [@json.name "EmbedderDomDistillerSelfDeletingRequestDelegate"]
  | EmbedderOomInterventionTabHelper [@json.name "EmbedderOomInterventionTabHelper"]
  | EmbedderOfflinePage [@json.name "EmbedderOfflinePage"]
  | EmbedderChromePasswordManagerClientBindCredentialManager
    [@json.name "EmbedderChromePasswordManagerClientBindCredentialManager"]
  | EmbedderPermissionRequestManager [@json.name "EmbedderPermissionRequestManager"]
  | EmbedderModalDialog [@json.name "EmbedderModalDialog"]
  | EmbedderExtensions [@json.name "EmbedderExtensions"]
  | EmbedderExtensionMessaging [@json.name "EmbedderExtensionMessaging"]
  | EmbedderExtensionMessagingForOpenPort [@json.name "EmbedderExtensionMessagingForOpenPort"]
  | EmbedderExtensionSentMessageToCachedFrame [@json.name "EmbedderExtensionSentMessageToCachedFrame"]
  | EmbedderExtensionFrame [@json.name "EmbedderExtensionFrame"]
  | EmbedderPrivilegedWebContents [@json.name "EmbedderPrivilegedWebContents"]
  | RequestedByWebViewClient [@json.name "RequestedByWebViewClient"]
  | PostMessageByWebViewClient [@json.name "PostMessageByWebViewClient"]
  | CacheControlNoStoreDeviceBoundSessionTerminated [@json.name "CacheControlNoStoreDeviceBoundSessionTerminated"]
  | CacheLimitPrunedOnModerateMemoryPressure [@json.name "CacheLimitPrunedOnModerateMemoryPressure"]
  | CacheLimitPrunedOnCriticalMemoryPressure [@json.name "CacheLimitPrunedOnCriticalMemoryPressure"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and back_forward_cache_not_restored_reason_type =
  | SupportPending [@json.name "SupportPending"]
  | PageSupportNeeded [@json.name "PageSupportNeeded"]
  | Circumstantial [@json.name "Circumstantial"]
  | Other of Cdp_json.unknown [@json.catch_all]
[@@compact_variants] [@@alert experimental "experimental in CDP, may change with Chrome"]

and back_forward_cache_blocking_details = {
  url : string option; [@key "url"] [@option] [@json.drop_default]
  function_ : string option; [@key "function"] [@option] [@json.drop_default]
  line_number : int; [@key "lineNumber"]
  column_number : int; [@key "columnNumber"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and back_forward_cache_not_restored_explanation = {
  type_ : back_forward_cache_not_restored_reason_type; [@key "type"]
  reason : back_forward_cache_not_restored_reason; [@key "reason"]
  context : string option; [@key "context"] [@option] [@json.drop_default]
  details : back_forward_cache_blocking_details list option; [@key "details"] [@option] [@json.drop_default]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"]

and back_forward_cache_not_restored_explanation_tree = {
  url : string; [@key "url"]
  explanations : back_forward_cache_not_restored_explanation list; [@key "explanations"]
  children : back_forward_cache_not_restored_explanation_tree list; [@key "children"]
}
[@@allow_extra_fields] [@@alert experimental "experimental in CDP, may change with Chrome"] [@@deriving json, show, eq]
