(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)
(* Sealed modules for every primitive alias type. This file depends on
   nothing, so alias references can never create a module cycle. *)

module Browser = struct
  module Browser_context_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@alert experimental "experimental in CDP, may change with Chrome"]

  module Window_id : sig
    type t
    val of_int : int -> t
    val to_int : t -> int
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = int
    let of_int value = value
    let to_int value = value
    let equal = Int.equal
    let compare = Int.compare
    let show (value : t) = string_of_int value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.int_of_json
    let to_json = Jsonkit.Primitives.int_to_json
  end
  [@@alert experimental "experimental in CDP, may change with Chrome"]
end

module Dom = struct
  module Node_id : sig
    type t
    val of_int : int -> t
    val to_int : t -> int
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = int
    let of_int value = value
    let to_int value = value
    let equal = Int.equal
    let compare = Int.compare
    let show (value : t) = string_of_int value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.int_of_json
    let to_json = Jsonkit.Primitives.int_to_json
  end

  module Backend_node_id : sig
    type t
    val of_int : int -> t
    val to_int : t -> int
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = int
    let of_int value = value
    let to_int value = value
    let equal = Int.equal
    let compare = Int.compare
    let show (value : t) = string_of_int value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.int_of_json
    let to_json = Jsonkit.Primitives.int_to_json
  end

  module Style_sheet_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
end

module Emulation = struct
  module Screen_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@alert experimental "experimental in CDP, may change with Chrome"]
end

module Io = struct
  module Stream_handle : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
end

module Network = struct
  module Loader_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end

  module Request_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end

  module Time_since_epoch : sig
    type t
    val of_float : float -> t
    val to_float : t -> float
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = float
    let of_float value = value
    let to_float value = value
    let equal = Float.equal
    let compare = Float.compare
    let show (value : t) = string_of_float value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Cdp_json.number_of_json
    let to_json = Cdp_json.number_to_json
  end

  module Monotonic_time : sig
    type t
    val of_float : float -> t
    val to_float : t -> float
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = float
    let of_float value = value
    let to_float value = value
    let equal = Float.equal
    let compare = Float.compare
    let show (value : t) = string_of_float value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Cdp_json.number_of_json
    let to_json = Cdp_json.number_to_json
  end

  module Report_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@alert experimental "experimental in CDP, may change with Chrome"]

  module Device_bound_session_event_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@alert experimental "experimental in CDP, may change with Chrome"]
end

module Page = struct
  module Frame_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end

  module Script_identifier : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
end

module Security = struct
  module Certificate_id : sig
    type t
    val of_int : int -> t
    val to_int : t -> int
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = int
    let of_int value = value
    let to_int value = value
    let equal = Int.equal
    let compare = Int.compare
    let show (value : t) = string_of_int value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.int_of_json
    let to_json = Jsonkit.Primitives.int_to_json
  end
end

module Target = struct
  module Target_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end

  module Session_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
end

module Debugger = struct
  module Breakpoint_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end

  module Call_frame_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
end

module Runtime = struct
  module Script_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end

  module Remote_object_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end

  module Unserializable_value : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end

  module Execution_context_id : sig
    type t
    val of_int : int -> t
    val to_int : t -> int
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = int
    let of_int value = value
    let to_int value = value
    let equal = Int.equal
    let compare = Int.compare
    let show (value : t) = string_of_int value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.int_of_json
    let to_json = Jsonkit.Primitives.int_to_json
  end

  module Timestamp : sig
    type t
    val of_float : float -> t
    val to_float : t -> float
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = float
    let of_float value = value
    let to_float value = value
    let equal = Float.equal
    let compare = Float.compare
    let show (value : t) = string_of_float value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Cdp_json.number_of_json
    let to_json = Cdp_json.number_to_json
  end

  module Time_delta : sig
    type t
    val of_float : float -> t
    val to_float : t -> float
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = float
    let of_float value = value
    let to_float value = value
    let equal = Float.equal
    let compare = Float.compare
    let show (value : t) = string_of_float value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Cdp_json.number_of_json
    let to_json = Cdp_json.number_to_json
  end

  module Unique_debugger_id : sig
    type t
    val of_string : string -> t
    val to_string : t -> string
    val equal : t -> t -> bool
    val compare : t -> t -> int
    val pp : Format.formatter -> t -> unit
    val show : t -> string
    val of_json : Jsonkit.t -> t
    val to_json : t -> Jsonkit.t
  end = struct
    type t = string
    let of_string value = value
    let to_string value = value
    let equal = String.equal
    let compare = String.compare
    let show (value : t) = Printf.sprintf "%S" value
    let pp fmt value = Format.pp_print_string fmt (show value)
    let of_json = Jsonkit.Primitives.string_of_json
    let to_json = Jsonkit.Primitives.string_to_json
  end
  [@@alert experimental "experimental in CDP, may change with Chrome"]
end
