(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)

include Cdp_page_types
open Jsonkit.Primitives

module Add_script_to_evaluate_on_load = struct
  let name = "Page.addScriptToEvaluateOnLoad"

  type params = { script_source : string [@key "scriptSource"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { identifier : Cdp_base.Page.Script_identifier.t [@key "identifier"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Add_script_to_evaluate_on_new_document = struct
  let name = "Page.addScriptToEvaluateOnNewDocument"

  type params = {
    source : string; [@key "source"]
    world_name : string option;
       [@key "worldName"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    include_command_line_api : bool option;
       [@key "includeCommandLineAPI"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    run_immediately : bool option;
       [@key "runImmediately"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { identifier : Cdp_base.Page.Script_identifier.t [@key "identifier"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Bring_to_front = struct
  let name = "Page.bringToFront"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Capture_screenshot = struct
  let name = "Page.captureScreenshot"

  type format =
    | Jpeg [@json.name "jpeg"]
    | Png [@json.name "png"]
    | Webp [@json.name "webp"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    format : format option; [@key "format"] [@option] [@json.drop_default]
    quality : int option; [@key "quality"] [@option] [@json.drop_default]
    clip : viewport option; [@key "clip"] [@option] [@json.drop_default]
    from_surface : bool option;
       [@key "fromSurface"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    capture_beyond_viewport : bool option;
       [@key "captureBeyondViewport"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    optimize_for_speed : bool option;
       [@key "optimizeForSpeed"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { data : string [@key "data"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Capture_snapshot = struct
  let name = "Page.captureSnapshot"

  type format =
    | Mhtml [@json.name "mhtml"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = { format : format option [@key "format"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { data : string [@key "data"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Clear_device_metrics_override = struct
  let name = "Page.clearDeviceMetricsOverride"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Clear_device_orientation_override = struct
  let name = "Page.clearDeviceOrientationOverride"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Clear_geolocation_override = struct
  let name = "Page.clearGeolocationOverride"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Create_isolated_world = struct
  let name = "Page.createIsolatedWorld"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    world_name : string option; [@key "worldName"] [@option] [@json.drop_default]
    grant_univeral_access : bool option; [@key "grantUniveralAccess"] [@option] [@json.drop_default]
    content_security_policy : string option; [@key "contentSecurityPolicy"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { execution_context_id : Cdp_base.Runtime.Execution_context_id.t [@key "executionContextId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Delete_cookie = struct
  let name = "Page.deleteCookie"

  type params = {
    cookie_name : string; [@key "cookieName"]
    url : string; [@key "url"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Disable = struct
  let name = "Page.disable"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Enable = struct
  let name = "Page.enable"

  type params = {
    enable_file_chooser_opened_event : bool option;
       [@key "enableFileChooserOpenedEvent"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_app_manifest = struct
  let name = "Page.getAppManifest"

  type params = { manifest_id : string option [@key "manifestId"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    url : string; [@key "url"]
    errors : app_manifest_error list; [@key "errors"]
    data : string option; [@key "data"] [@option] [@json.drop_default]
    parsed : app_manifest_parsed_properties option;
       [@key "parsed"]
       [@option]
       [@json.drop_default]
       [@ocaml.deprecated "deprecated in CDP"]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    manifest : web_app_manifest; [@key "manifest"] [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_installability_errors = struct
  let name = "Page.getInstallabilityErrors"

  type result = { installability_errors : installability_error list [@key "installabilityErrors"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_manifest_icons = struct
  let name = "Page.getManifestIcons"

  type result = { primary_icon : string option [@key "primaryIcon"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_app_id = struct
  let name = "Page.getAppId"

  type result = {
    app_id : string option; [@key "appId"] [@option] [@json.drop_default]
    recommended_id : string option; [@key "recommendedId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_ad_script_ancestry = struct
  let name = "Page.getAdScriptAncestry"

  type params = { frame_id : Cdp_base.Page.Frame_id.t [@key "frameId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    ad_script_ancestry : Cdp_network_types.ad_ancestry option; [@key "adScriptAncestry"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_frame_tree = struct
  let name = "Page.getFrameTree"

  type result = { frame_tree : frame_tree [@key "frameTree"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Get_layout_metrics = struct
  let name = "Page.getLayoutMetrics"

  type result = {
    layout_viewport : layout_viewport; [@key "layoutViewport"] [@ocaml.deprecated "deprecated in CDP"]
    visual_viewport : visual_viewport; [@key "visualViewport"] [@ocaml.deprecated "deprecated in CDP"]
    content_size : Cdp_dom_types.rect; [@key "contentSize"] [@ocaml.deprecated "deprecated in CDP"]
    css_layout_viewport : layout_viewport; [@key "cssLayoutViewport"]
    css_visual_viewport : visual_viewport; [@key "cssVisualViewport"]
    css_content_size : Cdp_dom_types.rect; [@key "cssContentSize"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Get_navigation_history = struct
  let name = "Page.getNavigationHistory"

  type result = {
    current_index : int; [@key "currentIndex"]
    entries : navigation_entry list; [@key "entries"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Reset_navigation_history = struct
  let name = "Page.resetNavigationHistory"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Get_resource_content = struct
  let name = "Page.getResourceContent"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    url : string; [@key "url"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    content : string; [@key "content"]
    base64_encoded : bool; [@key "base64Encoded"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_resource_tree = struct
  let name = "Page.getResourceTree"

  type result = { frame_tree : frame_resource_tree [@key "frameTree"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Handle_java_script_dialog = struct
  let name = "Page.handleJavaScriptDialog"

  type params = {
    accept : bool; [@key "accept"]
    prompt_text : string option; [@key "promptText"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Navigate = struct
  let name = "Page.navigate"

  type params = {
    url : string; [@key "url"]
    referrer : string option; [@key "referrer"] [@option] [@json.drop_default]
    transition_type : transition_type option; [@key "transitionType"] [@option] [@json.drop_default]
    frame_id : Cdp_base.Page.Frame_id.t option; [@key "frameId"] [@option] [@json.drop_default]
    referrer_policy : referrer_policy option;
       [@key "referrerPolicy"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    loader_id : Cdp_base.Network.Loader_id.t option; [@key "loaderId"] [@option] [@json.drop_default]
    error_text : string option; [@key "errorText"] [@option] [@json.drop_default]
    is_download : bool option;
       [@key "isDownload"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Navigate_to_history_entry = struct
  let name = "Page.navigateToHistoryEntry"

  type params = { entry_id : int [@key "entryId"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Print_to_pdf = struct
  let name = "Page.printToPDF"

  type transfer_mode =
    | ReturnAsBase64 [@json.name "ReturnAsBase64"]
    | ReturnAsStream [@json.name "ReturnAsStream"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    landscape : bool option; [@key "landscape"] [@option] [@json.drop_default]
    display_header_footer : bool option; [@key "displayHeaderFooter"] [@option] [@json.drop_default]
    print_background : bool option; [@key "printBackground"] [@option] [@json.drop_default]
    scale : float option; [@key "scale"] [@option] [@json.drop_default]
    paper_width : float option; [@key "paperWidth"] [@option] [@json.drop_default]
    paper_height : float option; [@key "paperHeight"] [@option] [@json.drop_default]
    margin_top : float option; [@key "marginTop"] [@option] [@json.drop_default]
    margin_bottom : float option; [@key "marginBottom"] [@option] [@json.drop_default]
    margin_left : float option; [@key "marginLeft"] [@option] [@json.drop_default]
    margin_right : float option; [@key "marginRight"] [@option] [@json.drop_default]
    page_ranges : string option; [@key "pageRanges"] [@option] [@json.drop_default]
    header_template : string option; [@key "headerTemplate"] [@option] [@json.drop_default]
    footer_template : string option; [@key "footerTemplate"] [@option] [@json.drop_default]
    prefer_css_page_size : bool option; [@key "preferCSSPageSize"] [@option] [@json.drop_default]
    transfer_mode : transfer_mode option;
       [@key "transferMode"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    generate_tagged_pdf : bool option;
       [@key "generateTaggedPDF"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    generate_document_outline : bool option;
       [@key "generateDocumentOutline"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    data : string; [@key "data"]
    stream : Cdp_base.Io.Stream_handle.t option;
       [@key "stream"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Reload = struct
  let name = "Page.reload"

  type params = {
    ignore_cache : bool option; [@key "ignoreCache"] [@option] [@json.drop_default]
    script_to_evaluate_on_load : string option; [@key "scriptToEvaluateOnLoad"] [@option] [@json.drop_default]
    loader_id : Cdp_base.Network.Loader_id.t option;
       [@key "loaderId"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Remove_script_to_evaluate_on_load = struct
  let name = "Page.removeScriptToEvaluateOnLoad"

  type params = { identifier : Cdp_base.Page.Script_identifier.t [@key "identifier"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Remove_script_to_evaluate_on_new_document = struct
  let name = "Page.removeScriptToEvaluateOnNewDocument"

  type params = { identifier : Cdp_base.Page.Script_identifier.t [@key "identifier"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Screencast_frame_ack = struct
  let name = "Page.screencastFrameAck"

  type params = { session_id : int [@key "sessionId"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Search_in_resource = struct
  let name = "Page.searchInResource"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    url : string; [@key "url"]
    query : string; [@key "query"]
    case_sensitive : bool option; [@key "caseSensitive"] [@option] [@json.drop_default]
    is_regex : bool option; [@key "isRegex"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { result : Cdp_debugger_types.search_match list [@key "result"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_ad_blocking_enabled = struct
  let name = "Page.setAdBlockingEnabled"

  type params = { enabled : bool [@key "enabled"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_bypass_csp = struct
  let name = "Page.setBypassCSP"

  type params = { enabled : bool [@key "enabled"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_permissions_policy_state = struct
  let name = "Page.getPermissionsPolicyState"

  type params = { frame_id : Cdp_base.Page.Frame_id.t [@key "frameId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { states : permissions_policy_feature_state list [@key "states"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_origin_trials = struct
  let name = "Page.getOriginTrials"

  type params = { frame_id : Cdp_base.Page.Frame_id.t [@key "frameId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { origin_trials : origin_trial list [@key "originTrials"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_device_metrics_override = struct
  let name = "Page.setDeviceMetricsOverride"

  type params = {
    width : int; [@key "width"]
    height : int; [@key "height"]
    device_scale_factor : float; [@key "deviceScaleFactor"]
    mobile : bool; [@key "mobile"]
    scale : float option; [@key "scale"] [@option] [@json.drop_default]
    screen_width : int option; [@key "screenWidth"] [@option] [@json.drop_default]
    screen_height : int option; [@key "screenHeight"] [@option] [@json.drop_default]
    position_x : int option; [@key "positionX"] [@option] [@json.drop_default]
    position_y : int option; [@key "positionY"] [@option] [@json.drop_default]
    dont_set_visible_size : bool option; [@key "dontSetVisibleSize"] [@option] [@json.drop_default]
    screen_orientation : Cdp_emulation_types.screen_orientation option;
       [@key "screenOrientation"] [@option] [@json.drop_default]
    viewport : viewport option; [@key "viewport"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_device_orientation_override = struct
  let name = "Page.setDeviceOrientationOverride"

  type params = {
    alpha : float; [@key "alpha"]
    beta : float; [@key "beta"]
    gamma : float; [@key "gamma"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_font_families = struct
  let name = "Page.setFontFamilies"

  type params = {
    font_families : font_families; [@key "fontFamilies"]
    for_scripts : script_font_families list option; [@key "forScripts"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_font_sizes = struct
  let name = "Page.setFontSizes"

  type params = { font_sizes : font_sizes [@key "fontSizes"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_document_content = struct
  let name = "Page.setDocumentContent"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    html : string; [@key "html"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_download_behavior = struct
  let name = "Page.setDownloadBehavior"

  type behavior =
    | Deny [@json.name "deny"]
    | Allow [@json.name "allow"]
    | Default [@json.name "default"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    behavior : behavior; [@key "behavior"]
    download_path : string option; [@key "downloadPath"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_geolocation_override = struct
  let name = "Page.setGeolocationOverride"

  type params = {
    latitude : float option; [@key "latitude"] [@option] [@json.drop_default]
    longitude : float option; [@key "longitude"] [@option] [@json.drop_default]
    accuracy : float option; [@key "accuracy"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Set_lifecycle_events_enabled = struct
  let name = "Page.setLifecycleEventsEnabled"

  type params = { enabled : bool [@key "enabled"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_touch_emulation_enabled = struct
  let name = "Page.setTouchEmulationEnabled"

  type configuration =
    | Mobile [@json.name "mobile"]
    | Desktop [@json.name "desktop"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    enabled : bool; [@key "enabled"]
    configuration : configuration option; [@key "configuration"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Start_screencast = struct
  let name = "Page.startScreencast"

  type format =
    | Jpeg [@json.name "jpeg"]
    | Png [@json.name "png"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    format : format option; [@key "format"] [@option] [@json.drop_default]
    quality : int option; [@key "quality"] [@option] [@json.drop_default]
    max_width : int option; [@key "maxWidth"] [@option] [@json.drop_default]
    max_height : int option; [@key "maxHeight"] [@option] [@json.drop_default]
    every_nth_frame : int option; [@key "everyNthFrame"] [@option] [@json.drop_default]
    max_frames_in_flight : int option; [@key "maxFramesInFlight"] [@option] [@json.drop_default]
    send_last_frame : bool option; [@key "sendLastFrame"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Start_screen_recording = struct
  let name = "Page.startScreenRecording"

  type params = {
    audio : bool option; [@key "audio"] [@option] [@json.drop_default]
    max_width : int option; [@key "maxWidth"] [@option] [@json.drop_default]
    max_height : int option; [@key "maxHeight"] [@option] [@json.drop_default]
    frame_rate : int option; [@key "frameRate"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    stream : Cdp_base.Io.Stream_handle.t;
       [@key "stream"] [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Stop_screen_recording = struct
  let name = "Page.stopScreenRecording"

  type result = {
    stream : Cdp_base.Io.Stream_handle.t;
       [@key "stream"] [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Stop_loading = struct
  let name = "Page.stopLoading"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Crash = struct
  let name = "Page.crash"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Close = struct
  let name = "Page.close"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Set_web_lifecycle_state = struct
  let name = "Page.setWebLifecycleState"

  type state =
    | Frozen [@json.name "frozen"]
    | Active [@json.name "active"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = { state : state [@key "state"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Stop_screencast = struct
  let name = "Page.stopScreencast"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Produce_compilation_cache = struct
  let name = "Page.produceCompilationCache"

  type params = { scripts : compilation_cache_params list [@key "scripts"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Add_compilation_cache = struct
  let name = "Page.addCompilationCache"

  type params = {
    url : string; [@key "url"]
    data : string; [@key "data"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Clear_compilation_cache = struct
  let name = "Page.clearCompilationCache"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_spc_transaction_mode = struct
  let name = "Page.setSPCTransactionMode"

  type mode =
    | None_ [@json.name "none"]
    | AutoAccept [@json.name "autoAccept"]
    | AutoChooseToAuthAnotherWay [@json.name "autoChooseToAuthAnotherWay"]
    | AutoReject [@json.name "autoReject"]
    | AutoOptOut [@json.name "autoOptOut"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = { mode : mode [@key "mode"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_rph_registration_mode = struct
  let name = "Page.setRPHRegistrationMode"

  type mode =
    | None_ [@json.name "none"]
    | AutoAccept [@json.name "autoAccept"]
    | AutoReject [@json.name "autoReject"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = { mode : mode [@key "mode"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Generate_test_report = struct
  let name = "Page.generateTestReport"

  type params = {
    message : string; [@key "message"]
    group : string option; [@key "group"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Wait_for_debugger = struct
  let name = "Page.waitForDebugger"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_intercept_file_chooser_dialog = struct
  let name = "Page.setInterceptFileChooserDialog"

  type params = {
    enabled : bool; [@key "enabled"]
    cancel : bool option;
       [@key "cancel"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_prerendering_allowed = struct
  let name = "Page.setPrerenderingAllowed"

  type params = { is_allowed : bool [@key "isAllowed"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_annotated_page_content = struct
  let name = "Page.getAnnotatedPageContent"

  type params = {
    include_actionable_information : bool option; [@key "includeActionableInformation"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { content : string [@key "content"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Dom_content_event_fired = struct
  let name = "Page.domContentEventFired"

  type params = { timestamp : Cdp_base.Network.Monotonic_time.t [@key "timestamp"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module File_chooser_opened = struct
  let name = "Page.fileChooserOpened"

  type mode =
    | SelectSingle [@json.name "selectSingle"]
    | SelectMultiple [@json.name "selectMultiple"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t;
       [@key "frameId"] [@alert experimental "experimental in CDP, may change with Chrome"]
    mode : mode; [@key "mode"]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "backendNodeId"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Frame_attached = struct
  let name = "Page.frameAttached"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    parent_frame_id : Cdp_base.Page.Frame_id.t; [@key "parentFrameId"]
    stack : Cdp_runtime_types.stack_trace option; [@key "stack"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Frame_cleared_scheduled_navigation = struct
  let name = "Page.frameClearedScheduledNavigation"

  type params = { frame_id : Cdp_base.Page.Frame_id.t [@key "frameId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Frame_detached = struct
  let name = "Page.frameDetached"

  type reason =
    | Remove [@json.name "remove"]
    | Swap [@json.name "swap"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    reason : reason; [@key "reason"] [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Frame_subtree_will_be_detached = struct
  let name = "Page.frameSubtreeWillBeDetached"

  type params = { frame_id : Cdp_base.Page.Frame_id.t [@key "frameId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Frame_navigated = struct
  let name = "Page.frameNavigated"

  type params = {
    frame : frame; [@key "frame"]
    type_ : navigation_type; [@key "type"] [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Document_opened = struct
  let name = "Page.documentOpened"

  type params = { frame : frame [@key "frame"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Frame_resized = struct
  let name = "Page.frameResized"

  type params = unit [@@deriving show, eq]

  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Frame_started_navigating = struct
  let name = "Page.frameStartedNavigating"

  type navigation_type =
    | Reload [@json.name "reload"]
    | ReloadBypassingCache [@json.name "reloadBypassingCache"]
    | Restore [@json.name "restore"]
    | RestoreWithPost [@json.name "restoreWithPost"]
    | HistorySameDocument [@json.name "historySameDocument"]
    | HistoryDifferentDocument [@json.name "historyDifferentDocument"]
    | SameDocument [@json.name "sameDocument"]
    | DifferentDocument [@json.name "differentDocument"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    url : string; [@key "url"]
    loader_id : Cdp_base.Network.Loader_id.t; [@key "loaderId"]
    navigation_type : navigation_type; [@key "navigationType"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Frame_requested_navigation = struct
  let name = "Page.frameRequestedNavigation"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    reason : client_navigation_reason; [@key "reason"]
    url : string; [@key "url"]
    disposition : client_navigation_disposition; [@key "disposition"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Frame_scheduled_navigation = struct
  let name = "Page.frameScheduledNavigation"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    delay : float; [@key "delay"]
    reason : client_navigation_reason; [@key "reason"]
    url : string; [@key "url"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Frame_started_loading = struct
  let name = "Page.frameStartedLoading"

  type params = { frame_id : Cdp_base.Page.Frame_id.t [@key "frameId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Frame_stopped_loading = struct
  let name = "Page.frameStoppedLoading"

  type params = { frame_id : Cdp_base.Page.Frame_id.t [@key "frameId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Download_will_begin = struct
  let name = "Page.downloadWillBegin"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    guid : string; [@key "guid"]
    url : string; [@key "url"]
    suggested_filename : string; [@key "suggestedFilename"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Download_progress = struct
  let name = "Page.downloadProgress"

  type state =
    | InProgress [@json.name "inProgress"]
    | Completed [@json.name "completed"]
    | Canceled [@json.name "canceled"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    guid : string; [@key "guid"]
    total_bytes : float; [@key "totalBytes"]
    received_bytes : float; [@key "receivedBytes"]
    state : state; [@key "state"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Interstitial_hidden = struct
  let name = "Page.interstitialHidden"

  type params = unit [@@deriving show, eq]

  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Interstitial_shown = struct
  let name = "Page.interstitialShown"

  type params = unit [@@deriving show, eq]

  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Javascript_dialog_closed = struct
  let name = "Page.javascriptDialogClosed"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t;
       [@key "frameId"] [@alert experimental "experimental in CDP, may change with Chrome"]
    result : bool; [@key "result"]
    user_input : string; [@key "userInput"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Javascript_dialog_opening = struct
  let name = "Page.javascriptDialogOpening"

  type params = {
    url : string; [@key "url"]
    frame_id : Cdp_base.Page.Frame_id.t;
       [@key "frameId"] [@alert experimental "experimental in CDP, may change with Chrome"]
    message : string; [@key "message"]
    type_ : dialog_type; [@key "type"]
    has_browser_handler : bool; [@key "hasBrowserHandler"]
    default_prompt : string option; [@key "defaultPrompt"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Lifecycle_event = struct
  let name = "Page.lifecycleEvent"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    loader_id : Cdp_base.Network.Loader_id.t; [@key "loaderId"]
    name : string; [@key "name"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Back_forward_cache_not_used = struct
  let name = "Page.backForwardCacheNotUsed"

  type params = {
    loader_id : Cdp_base.Network.Loader_id.t; [@key "loaderId"]
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    not_restored_explanations : back_forward_cache_not_restored_explanation list; [@key "notRestoredExplanations"]
    not_restored_explanations_tree : back_forward_cache_not_restored_explanation_tree option;
       [@key "notRestoredExplanationsTree"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Load_event_fired = struct
  let name = "Page.loadEventFired"

  type params = { timestamp : Cdp_base.Network.Monotonic_time.t [@key "timestamp"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Navigated_within_document = struct
  let name = "Page.navigatedWithinDocument"

  type navigation_type =
    | Fragment [@json.name "fragment"]
    | HistoryApi [@json.name "historyApi"]
    | Other_ [@json.name "other"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"]
    url : string; [@key "url"]
    navigation_type : navigation_type; [@key "navigationType"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Screencast_frame = struct
  let name = "Page.screencastFrame"

  type params = {
    data : string; [@key "data"]
    metadata : screencast_frame_metadata; [@key "metadata"]
    session_id : int; [@key "sessionId"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Screencast_visibility_changed = struct
  let name = "Page.screencastVisibilityChanged"

  type params = { visible : bool [@key "visible"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Window_open = struct
  let name = "Page.windowOpen"

  type params = {
    url : string; [@key "url"]
    window_name : string; [@key "windowName"]
    window_features : string list; [@key "windowFeatures"]
    user_gesture : bool; [@key "userGesture"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Compilation_cache_produced = struct
  let name = "Page.compilationCacheProduced"

  type params = {
    url : string; [@key "url"]
    data : string; [@key "data"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]
