(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)

[@@@ocaml.doc
"This domain exposes DOM read/write operations. Each DOM Node is represented with its mirror object\n\
 that has an `id`. This `id` can be used to get additional information on the Node, resolve it into\n\
 the JavaScript object wrapper, etc. It is important that client receives DOM events only for the\n\
 nodes that are known to the client. Backend keeps track of the nodes that were sent to the client\n\
 and never sends the same node twice. It is client's responsibility to collect information about\n\
 the nodes that were sent to the client. Note that `iframe` owner elements will return\n\
 corresponding document elements as their child nodes."]

include Cdp_dom_types
open Jsonkit.Primitives

module Collect_class_names_from_subtree = struct
  let name = "DOM.collectClassNamesFromSubtree"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to collect class names."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { class_names : string list [@key "classNames"] [@ocaml.doc "Class name list."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Collects class names for the node with given id and all of it's child nodes."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Copy_to = struct
  let name = "DOM.copyTo"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to copy."]
    target_node_id : Cdp_base.Dom.Node_id.t;
       [@key "targetNodeId"] [@ocaml.doc "Id of the element to drop the copy into."]
    insert_before_node_id : Cdp_base.Dom.Node_id.t option;
       [@key "insertBeforeNodeId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Drop the copy before this node (if absent, the copy becomes the last child of\n`targetNodeId`)."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] [@ocaml.doc "Id of the node clone."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Creates a deep copy of the specified node and places it into the target container before the\ngiven anchor."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Describe_node = struct
  let name = "DOM.describeNode"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the node."]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "backendNodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the backend node."]
    object_id : Cdp_base.Runtime.Remote_object_id.t option;
       [@key "objectId"] [@option] [@json.drop_default] [@ocaml.doc "JavaScript object id of the node wrapper."]
    depth : int option;
       [@key "depth"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the\n\
          entire subtree or provide an integer larger than 0."]
    pierce : bool option;
       [@key "pierce"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Whether or not iframes and shadow roots should be traversed when returning the subtree\n(default is false)."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node : node [@key "node"] [@ocaml.doc "Node description."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Describes node given its id, does not require domain to be enabled. Does not start tracking any\n\
   objects, can be used for automation."]

module Scroll_into_view_if_needed = struct
  let name = "DOM.scrollIntoViewIfNeeded"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the node."]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "backendNodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the backend node."]
    object_id : Cdp_base.Runtime.Remote_object_id.t option;
       [@key "objectId"] [@option] [@json.drop_default] [@ocaml.doc "JavaScript object id of the node wrapper."]
    rect : rect option;
       [@key "rect"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "The rect to be scrolled into view, relative to the node's border box, in CSS pixels.\n\
          When omitted, center of the node will be used, similar to Element.scrollIntoView."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Scrolls the specified rect of the given node into view if not already visible.\n\
   Note: exactly one between nodeId, backendNodeId and objectId should be passed\n\
   to identify the node."]

module Disable = struct
  let name = "DOM.disable"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Disables DOM agent for the given page."]

module Discard_search_results = struct
  let name = "DOM.discardSearchResults"

  type params = { search_id : string [@key "searchId"] [@ocaml.doc "Unique search session identifier."] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Discards search results from the session with the given id. `getSearchResults` should no longer\n\
   be called for that search."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Enable = struct
  let name = "DOM.enable"

  type include_whitespace =
    | None_ [@json.name "none"]
    | All [@json.name "all"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    include_whitespace : include_whitespace option;
       [@key "includeWhitespace"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Whether to include whitespaces in the children array of returned Nodes."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Enables DOM agent for the given page."]

module Focus = struct
  let name = "DOM.focus"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the node."]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "backendNodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the backend node."]
    object_id : Cdp_base.Runtime.Remote_object_id.t option;
       [@key "objectId"] [@option] [@json.drop_default] [@ocaml.doc "JavaScript object id of the node wrapper."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Focuses the given element."]

module Get_attributes = struct
  let name = "DOM.getAttributes"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to retrieve attributes for."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    attributes : string list; [@key "attributes"] [@ocaml.doc "An interleaved array of node attribute names and values."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Returns attributes for the specified node."]

module Get_box_model = struct
  let name = "DOM.getBoxModel"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the node."]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "backendNodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the backend node."]
    object_id : Cdp_base.Runtime.Remote_object_id.t option;
       [@key "objectId"] [@option] [@json.drop_default] [@ocaml.doc "JavaScript object id of the node wrapper."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { model : box_model [@key "model"] [@ocaml.doc "Box model for the node."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Returns boxes for the given node."]

module Get_content_quads = struct
  let name = "DOM.getContentQuads"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the node."]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "backendNodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the backend node."]
    object_id : Cdp_base.Runtime.Remote_object_id.t option;
       [@key "objectId"] [@option] [@json.drop_default] [@ocaml.doc "JavaScript object id of the node wrapper."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    quads : quad list; [@key "quads"] [@ocaml.doc "Quads that describe node layout relative to viewport."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Returns quads that describe node position on the page. This method\nmight return multiple quads for inline nodes."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_document = struct
  let name = "DOM.getDocument"

  type params = {
    depth : int option;
       [@key "depth"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the\n\
          entire subtree or provide an integer larger than 0."]
    pierce : bool option;
       [@key "pierce"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Whether or not iframes and shadow roots should be traversed when returning the subtree\n(default is false)."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { root : node [@key "root"] [@ocaml.doc "Resulting node."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Returns the root DOM node (and optionally the subtree) to the caller.\n\
   Implicitly enables the DOM domain events for the current target."]

module Get_flattened_document = struct
  let name = "DOM.getFlattenedDocument"

  type params = {
    depth : int option;
       [@key "depth"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the\n\
          entire subtree or provide an integer larger than 0."]
    pierce : bool option;
       [@key "pierce"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Whether or not iframes and shadow roots should be traversed when returning the subtree\n(default is false)."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { nodes : node list [@key "nodes"] [@ocaml.doc "Resulting node."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Returns the root DOM node (and optionally the subtree) to the caller.\n\
   Deprecated, as it is not designed to work well with the rest of the DOM agent.\n\
   Use DOMSnapshot.captureSnapshot instead."]
[@@ocaml.deprecated "deprecated in CDP"]

module Get_nodes_for_subtree_by_style = struct
  let name = "DOM.getNodesForSubtreeByStyle"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Node ID pointing to the root of a subtree."]
    computed_styles : css_computed_style_property list;
       [@key "computedStyles"]
       [@ocaml.doc "The style to filter nodes by (includes nodes if any of properties matches)."]
    pierce : bool option;
       [@key "pierce"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Whether or not iframes and shadow roots in the same target should be traversed when returning the\n\
          results (default is false)."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] [@ocaml.doc "Resulting nodes."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Finds nodes with a given computed style in a subtree."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_node_for_location = struct
  let name = "DOM.getNodeForLocation"

  type params = {
    x : int; [@key "x"] [@ocaml.doc "X coordinate."]
    y : int; [@key "y"] [@ocaml.doc "Y coordinate."]
    include_user_agent_shadow_dom : bool option;
       [@key "includeUserAgentShadowDOM"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "False to skip to the nearest non-UA shadow root ancestor (default: false)."]
    ignore_pointer_events_none : bool option;
       [@key "ignorePointerEventsNone"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Whether to ignore pointer-events: none on elements and hit test them."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    backend_node_id : Cdp_base.Dom.Backend_node_id.t; [@key "backendNodeId"] [@ocaml.doc "Resulting node."]
    frame_id : Cdp_base.Page.Frame_id.t; [@key "frameId"] [@ocaml.doc "Frame this node belongs to."]
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Id of the node at given coordinates, only when enabled and requested document."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Returns node id at given location. Depending on whether DOM domain is enabled, nodeId is\neither returned or not."]

module Get_outer_html = struct
  let name = "DOM.getOuterHTML"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the node."]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "backendNodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the backend node."]
    object_id : Cdp_base.Runtime.Remote_object_id.t option;
       [@key "objectId"] [@option] [@json.drop_default] [@ocaml.doc "JavaScript object id of the node wrapper."]
    include_shadow_dom : bool option;
       [@key "includeShadowDOM"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "Include all shadow roots. Equals to false if not specified."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { outer_html : string [@key "outerHTML"] [@ocaml.doc "Outer HTML markup."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Returns node's HTML markup."]

module Get_relayout_boundary = struct
  let name = "DOM.getRelayoutBoundary"

  type params = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] [@ocaml.doc "Id of the node."] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Relayout boundary node id for the given node."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Returns the id of the nearest ancestor that is a relayout boundary."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_search_results = struct
  let name = "DOM.getSearchResults"

  type params = {
    search_id : string; [@key "searchId"] [@ocaml.doc "Unique search session identifier."]
    from_index : int; [@key "fromIndex"] [@ocaml.doc "Start index of the search result to be returned."]
    to_index : int; [@key "toIndex"] [@ocaml.doc "End index of the search result to be returned."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    node_ids : Cdp_base.Dom.Node_id.t list; [@key "nodeIds"] [@ocaml.doc "Ids of the search result nodes."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Returns search results from given `fromIndex` to given `toIndex` from the search with the given\nidentifier."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Hide_highlight = struct
  let name = "DOM.hideHighlight"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Hides any highlight."] [@@alert redirected "redirected to the Overlay domain in CDP"]

module Highlight_node = struct
  let name = "DOM.highlightNode"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Highlights DOM node."] [@@alert redirected "redirected to the Overlay domain in CDP"]

module Highlight_rect = struct
  let name = "DOM.highlightRect"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Highlights given rectangle."] [@@alert redirected "redirected to the Overlay domain in CDP"]

module Mark_undoable_state = struct
  let name = "DOM.markUndoableState"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Marks last undoable state."] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Move_to = struct
  let name = "DOM.moveTo"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to move."]
    target_node_id : Cdp_base.Dom.Node_id.t;
       [@key "targetNodeId"] [@ocaml.doc "Id of the element to drop the moved node into."]
    insert_before_node_id : Cdp_base.Dom.Node_id.t option;
       [@key "insertBeforeNodeId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Drop node before this one (if absent, the moved node becomes the last child of\n`targetNodeId`)."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] [@ocaml.doc "New id of the moved node."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Moves node into the new container, places it before the given anchor."]

module Perform_search = struct
  let name = "DOM.performSearch"

  type params = {
    query : string; [@key "query"] [@ocaml.doc "Plain text or query selector or XPath search query."]
    include_user_agent_shadow_dom : bool option;
       [@key "includeUserAgentShadowDOM"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "True to search in user agent shadow DOM."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    search_id : string; [@key "searchId"] [@ocaml.doc "Unique search session identifier."]
    result_count : int; [@key "resultCount"] [@ocaml.doc "Number of search results."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Searches for a given string in the DOM tree. Use `getSearchResults` to access search results or\n\
   `cancelSearch` to end this search session."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Push_node_by_path_to_frontend = struct
  let name = "DOM.pushNodeByPathToFrontend"

  type params = { path : string [@key "path"] [@ocaml.doc "Path to node in the proprietary format."] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] [@ocaml.doc "Id of the node for given path."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Requests that the node is sent to the caller given its path. // FIXME, use XPath"]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Push_nodes_by_backend_ids_to_frontend = struct
  let name = "DOM.pushNodesByBackendIdsToFrontend"

  type params = {
    backend_node_ids : Cdp_base.Dom.Backend_node_id.t list;
       [@key "backendNodeIds"] [@ocaml.doc "The array of backend node ids."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    node_ids : Cdp_base.Dom.Node_id.t list;
       [@key "nodeIds"]
       [@ocaml.doc "The array of ids of pushed nodes that correspond to the backend ids specified in\nbackendNodeIds."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Requests that a batch of nodes is sent to the caller given their backend node ids."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Query_selector = struct
  let name = "DOM.querySelector"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to query upon."]
    selector : string; [@key "selector"] [@ocaml.doc "Selector string."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] [@ocaml.doc "Query selector result."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Executes `querySelector` on a given node."]

module Query_selector_all = struct
  let name = "DOM.querySelectorAll"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to query upon."]
    selector : string; [@key "selector"] [@ocaml.doc "Selector string."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] [@ocaml.doc "Query selector result."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Executes `querySelectorAll` on a given node."]

module Get_top_layer_elements = struct
  let name = "DOM.getTopLayerElements"

  type result = { node_ids : Cdp_base.Dom.Node_id.t list [@key "nodeIds"] [@ocaml.doc "NodeIds of top layer elements"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc
  "Returns NodeIds of current top layer elements.\n\
   Top layer is rendered closest to the user within a viewport, therefore its elements always\n\
   appear on top of all other content."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_element_by_relation = struct
  let name = "DOM.getElementByRelation"

  type relation =
    | PopoverTarget [@json.name "PopoverTarget"]
    | InterestTarget [@json.name "InterestTarget"]
    | CommandFor [@json.name "CommandFor"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node from which to query the relation."]
    relation : relation; [@key "relation"] [@ocaml.doc "Type of relation to get."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "NodeId of the element matching the queried relation."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Returns the NodeId of the matched element according to certain relations."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Redo = struct
  let name = "DOM.redo"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Re-does the last undone action."] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Remove_attribute = struct
  let name = "DOM.removeAttribute"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the element to remove attribute from."]
    name : string; [@key "name"] [@ocaml.doc "Name of the attribute to remove."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Removes attribute with given name from an element with given id."]

module Remove_node = struct
  let name = "DOM.removeNode"

  type params = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] [@ocaml.doc "Id of the node to remove."] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Removes node with given id."]

module Request_child_nodes = struct
  let name = "DOM.requestChildNodes"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to get children for."]
    depth : int option;
       [@key "depth"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "The maximum depth at which children should be retrieved, defaults to 1. Use -1 for the\n\
          entire subtree or provide an integer larger than 0."]
    pierce : bool option;
       [@key "pierce"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Whether or not iframes and shadow roots should be traversed when returning the sub-tree\n(default is false)."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Requests that children of the node with given id are returned to the caller in form of\n\
   `setChildNodes` events where not only immediate children are retrieved, but all children down to\n\
   the specified depth."]

module Request_node = struct
  let name = "DOM.requestNode"

  type params = {
    object_id : Cdp_base.Runtime.Remote_object_id.t;
       [@key "objectId"] [@ocaml.doc "JavaScript object id to convert into node."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] [@ocaml.doc "Node id for given object."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Requests that the node is sent to the caller given the JavaScript node object reference. All\n\
   nodes that form the path from the node to the root are also sent to the client as a series of\n\
   `setChildNodes` notifications."]

module Resolve_node = struct
  let name = "DOM.resolveNode"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"] [@option] [@json.drop_default] [@ocaml.doc "Id of the node to resolve."]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "backendNodeId"] [@option] [@json.drop_default] [@ocaml.doc "Backend identifier of the node to resolve."]
    object_group : string option;
       [@key "objectGroup"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Symbolic group name that can be used to release multiple objects."]
    execution_context_id : Cdp_base.Runtime.Execution_context_id.t option;
       [@key "executionContextId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Execution context in which to resolve the node."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    object_ : Cdp_runtime_types.remote_object; [@key "object"] [@ocaml.doc "JavaScript object wrapper for given node."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Resolves the JavaScript node object for a given NodeId or BackendNodeId."]

module Set_attribute_value = struct
  let name = "DOM.setAttributeValue"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the element to set attribute for."]
    name : string; [@key "name"] [@ocaml.doc "Attribute name."]
    value : string; [@key "value"] [@ocaml.doc "Attribute value."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Sets attribute for an element with given id."]

module Set_attributes_as_text = struct
  let name = "DOM.setAttributesAsText"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the element to set attributes for."]
    text : string;
       [@key "text"] [@ocaml.doc "Text with a number of attributes. Will parse this text using HTML parser."]
    name : string option;
       [@key "name"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Attribute name to replace with new attributes derived from text in case text parsed\nsuccessfully."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Sets attributes on element with given id. This method is useful when user edits some existing\n\
   attribute value and types in several attribute name/value pairs."]

module Set_file_input_files = struct
  let name = "DOM.setFileInputFiles"

  type params = {
    files : string list; [@key "files"] [@ocaml.doc "Array of file paths to set."]
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the node."]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "backendNodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the backend node."]
    object_id : Cdp_base.Runtime.Remote_object_id.t option;
       [@key "objectId"] [@option] [@json.drop_default] [@ocaml.doc "JavaScript object id of the node wrapper."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Sets files for the given file input element."]

module Set_node_stack_traces_enabled = struct
  let name = "DOM.setNodeStackTracesEnabled"

  type params = { enable : bool [@key "enable"] [@ocaml.doc "Enable or disable."] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Sets if stack traces should be captured for Nodes. See `Node.getNodeStackTraces`. Default is disabled."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_node_stack_traces = struct
  let name = "DOM.getNodeStackTraces"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to get stack traces for."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    creation : Cdp_runtime_types.stack_trace option;
       [@key "creation"] [@option] [@json.drop_default] [@ocaml.doc "Creation stack trace, if available."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Gets stack traces associated with a Node. As of now, only provides stack trace for Node creation."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_file_info = struct
  let name = "DOM.getFileInfo"

  type params = {
    object_id : Cdp_base.Runtime.Remote_object_id.t;
       [@key "objectId"] [@ocaml.doc "JavaScript object id of the node wrapper."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { path : string [@key "path"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Returns file information for the given\nFile wrapper."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_detached_dom_nodes = struct
  let name = "DOM.getDetachedDomNodes"

  type result = {
    detached_nodes : detached_element_info list; [@key "detachedNodes"] [@ocaml.doc "The list of detached nodes"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Returns list of detached nodes"] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_inspected_node = struct
  let name = "DOM.setInspectedNode"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t;
       [@key "nodeId"] [@ocaml.doc "DOM node id to be accessible by means of $x command line API."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Enables console to refer to the node with given id via $x (see Command Line API for more details\n$x functions)."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_node_name = struct
  let name = "DOM.setNodeName"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to set name for."]
    name : string; [@key "name"] [@ocaml.doc "New node's name."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] [@ocaml.doc "New node's id."] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Sets node name for a node with given id."]

module Set_node_value = struct
  let name = "DOM.setNodeValue"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to set value for."]
    value : string; [@key "value"] [@ocaml.doc "New node's value."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Sets node value for a node with given id."]

module Set_outer_html = struct
  let name = "DOM.setOuterHTML"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node to set markup for."]
    outer_html : string; [@key "outerHTML"] [@ocaml.doc "Outer HTML markup to set."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Sets node HTML markup, returns new node id."]

module Undo = struct
  let name = "DOM.undo"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc "Undoes the last performed action."] [@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_frame_owner = struct
  let name = "DOM.getFrameOwner"

  type params = { frame_id : Cdp_base.Page.Frame_id.t [@key "frameId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    backend_node_id : Cdp_base.Dom.Backend_node_id.t; [@key "backendNodeId"] [@ocaml.doc "Resulting node."]
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "Id of the node at given coordinates, only when enabled and requested document."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Returns iframe node that owns iframe with the given domain."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_container_for_node = struct
  let name = "DOM.getContainerForNode"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"]
    container_name : string option; [@key "containerName"] [@option] [@json.drop_default]
    physical_axes : physical_axes option; [@key "physicalAxes"] [@option] [@json.drop_default]
    logical_axes : logical_axes option; [@key "logicalAxes"] [@option] [@json.drop_default]
    queries_scroll_state : bool option; [@key "queriesScrollState"] [@option] [@json.drop_default]
    queries_anchored : bool option; [@key "queriesAnchored"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "The container node for the given node, or null if not found."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Returns the query container of the given node based on container query\n\
   conditions: containerName, physical and logical axes, and whether it queries\n\
   scroll-state or anchored elements. If no axes are provided and\n\
   queriesScrollState is false, the style container is returned, which is the\n\
   direct parent or the closest element with a matching container-name."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_querying_descendants_for_container = struct
  let name = "DOM.getQueryingDescendantsForContainer"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t;
       [@key "nodeId"] [@ocaml.doc "Id of the container node to find querying descendants from."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    node_ids : Cdp_base.Dom.Node_id.t list;
       [@key "nodeIds"] [@ocaml.doc "Descendant nodes with container queries against the given container."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Returns the descendants of a container query container that have\ncontainer queries against this container."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_anchor_element = struct
  let name = "DOM.getAnchorElement"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t;
       [@key "nodeId"] [@ocaml.doc "Id of the positioned element from which to find the anchor."]
    anchor_specifier : string option;
       [@key "anchorSpecifier"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "An optional anchor specifier, as defined in\n\
          https://www.w3.org/TR/css-anchor-position-1/#anchor-specifier.\n\
          If not provided, it will return the implicit anchor element for\n\
          the given positioned element."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "The anchor element of the given anchor query."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Returns the target anchor element of the given anchor query according to\n\
   https://www.w3.org/TR/css-anchor-position-1/#target."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Force_show_popover = struct
  let name = "DOM.forceShowPopover"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the popover HTMLElement"]
    enable : bool;
       [@key "enable"]
       [@ocaml.doc
         "If true, opens the popover and keeps it open. If false, closes the\n\
          popover if it was previously force-opened."]
    invoker_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "invokerNodeId"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc
         "Optional ID of the element invoking this popover, used to establish the implicit anchor.\n\
          If not provided, it will fall back to the first invoker in the document, preferring\n\
          elements with a popovertarget attribute over those with a commandfor attribute. Note that\n\
          if there are multiple invokers, this is just an estimate."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    node_ids : Cdp_base.Dom.Node_id.t list;
       [@key "nodeIds"] [@ocaml.doc "List of popovers that were closed in order to respect popover stacking order."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "When enabling, this API force-opens the popover identified by nodeId\nand keeps it open until disabled."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_implicit_anchor_candidates = struct
  let name = "DOM.getImplicitAnchorCandidates"

  type params = { node_id : Cdp_base.Dom.Node_id.t [@key "nodeId"] [@ocaml.doc "Id of the popover HTMLElement."] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    backend_node_ids : Cdp_base.Dom.Backend_node_id.t list;
       [@key "backendNodeIds"] [@ocaml.doc "Candidate elements that can invoke this popover."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc "Returns candidate nodes that are configured as triggers for the given popover."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Force_show_interest = struct
  let name = "DOM.forceShowInterest"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the interest invoker HTMLElement."]
    enable : bool; [@key "enable"] [@ocaml.doc "If true, opens and holds interest. If false, releases forced interest."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "When enabling, this API forces an element to gain interest in its target,\nkeeping interest active until disabled."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_text_marker = struct
  let name = "DOM.setTextMarker"

  type type_ =
    | Spelling [@json.name "spelling"]
    | Grammar [@json.name "grammar"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    node_id : Cdp_base.Dom.Node_id.t option;
       [@key "nodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the node."]
    backend_node_id : Cdp_base.Dom.Backend_node_id.t option;
       [@key "backendNodeId"] [@option] [@json.drop_default] [@ocaml.doc "Identifier of the backend node."]
    object_id : Cdp_base.Runtime.Remote_object_id.t option;
       [@key "objectId"] [@option] [@json.drop_default] [@ocaml.doc "JavaScript object id of the node wrapper."]
    type_ : type_; [@key "type"] [@ocaml.doc "The type of marker to set on the given range of text."]
    start : int;
       [@key "start"]
       [@ocaml.doc
         "Start offset into the element's rendered text in UTF-16 code units.\n\
          For a text control, an offset into the control's value.\n\
          Offsets count text in DOM order and do not enter shadow trees.\n\
          To mark text inside a shadow tree, pass the element inside the shadow tree."]
    end_ : int; [@key "end"] [@ocaml.doc "End offset (exclusive) in the same units and space as start."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.doc
  "Sets a spelling or grammar error marker on the given range of text.\n\
   See https://github.com/Igalia/explainers/blob/main/force-spelling-grammar-markers/README.md\n\
   Note: exactly one between nodeId, backendNodeId and objectId should be passed\n\
   to identify the node."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Clear_text_markers = struct
  let name = "DOM.clearTextMarkers"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.doc
  "Clears the spelling and grammar error text markers overlapping the ranges\n\
   set by setTextMarker in this session. These markers are also removed when\n\
   the DOM domain is disabled or the session ends."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Attribute_modified = struct
  let name = "DOM.attributeModified"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node that has changed."]
    name : string; [@key "name"] [@ocaml.doc "Attribute name."]
    value : string; [@key "value"] [@ocaml.doc "Attribute value."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Fired when `Element`'s attribute is modified."]

module Adopted_style_sheets_modified = struct
  let name = "DOM.adoptedStyleSheetsModified"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node that has changed."]
    adopted_style_sheets : Cdp_base.Dom.Style_sheet_id.t list;
       [@key "adoptedStyleSheets"]
       [@alert experimental "experimental in CDP, may change with Chrome"]
       [@ocaml.doc "New adoptedStyleSheets array."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Fired when `Element`'s adoptedStyleSheets are modified."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Attribute_removed = struct
  let name = "DOM.attributeRemoved"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node that has changed."]
    name : string; [@key "name"] [@ocaml.doc "A ttribute name."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Fired when `Element`'s attribute is removed."]

module Character_data_modified = struct
  let name = "DOM.characterDataModified"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node that has changed."]
    character_data : string; [@key "characterData"] [@ocaml.doc "New text value."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Mirrors `DOMCharacterDataModified` event."]

module Child_node_count_updated = struct
  let name = "DOM.childNodeCountUpdated"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node that has changed."]
    child_node_count : int; [@key "childNodeCount"] [@ocaml.doc "New node count."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Fired when `Container`'s child node count has changed."]

module Child_node_inserted = struct
  let name = "DOM.childNodeInserted"

  type params = {
    parent_node_id : Cdp_base.Dom.Node_id.t; [@key "parentNodeId"] [@ocaml.doc "Id of the node that has changed."]
    previous_node_id : Cdp_base.Dom.Node_id.t; [@key "previousNodeId"] [@ocaml.doc "Id of the previous sibling."]
    node : node; [@key "node"] [@ocaml.doc "Inserted node data."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Mirrors `DOMNodeInserted` event."]

module Child_node_removed = struct
  let name = "DOM.childNodeRemoved"

  type params = {
    parent_node_id : Cdp_base.Dom.Node_id.t; [@key "parentNodeId"] [@ocaml.doc "Parent id."]
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "Id of the node that has been removed."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Mirrors `DOMNodeRemoved` event."]

module Distributed_nodes_updated = struct
  let name = "DOM.distributedNodesUpdated"

  type params = {
    insertion_point_id : Cdp_base.Dom.Node_id.t;
       [@key "insertionPointId"] [@ocaml.doc "Insertion point where distributed nodes were updated."]
    distributed_nodes : backend_node list;
       [@key "distributedNodes"] [@ocaml.doc "Distributed nodes for given insertion point."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Called when distribution is changed."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Document_updated = struct
  let name = "DOM.documentUpdated"

  type params = unit [@@deriving show, eq]

  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Fired when `Document` has been totally updated. Node ids are no longer valid."]

module Inline_style_invalidated = struct
  let name = "DOM.inlineStyleInvalidated"

  type params = {
    node_ids : Cdp_base.Dom.Node_id.t list;
       [@key "nodeIds"] [@ocaml.doc "Ids of the nodes for which the inline styles have been invalidated."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Fired when `Element`'s inline style is modified via a CSS property modification."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Pseudo_element_added = struct
  let name = "DOM.pseudoElementAdded"

  type params = {
    parent_id : Cdp_base.Dom.Node_id.t; [@key "parentId"] [@ocaml.doc "Pseudo element's parent element id."]
    pseudo_element : node; [@key "pseudoElement"] [@ocaml.doc "The added pseudo element."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Called when a pseudo element is added to an element."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Top_layer_elements_updated = struct
  let name = "DOM.topLayerElementsUpdated"

  type params = unit [@@deriving show, eq]

  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Called when top layer elements are changed."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Scrollable_flag_updated = struct
  let name = "DOM.scrollableFlagUpdated"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "The id of the node."]
    is_scrollable : bool; [@key "isScrollable"] [@ocaml.doc "If the node is scrollable."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Fired when a node's scrollability state changes."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Ad_related_state_updated = struct
  let name = "DOM.adRelatedStateUpdated"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "The id of the node."]
    ad_provenance : Cdp_network_types.ad_provenance option;
       [@key "adProvenance"]
       [@option]
       [@json.drop_default]
       [@ocaml.doc "The provenance of the ad related node, if it is ad related."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Fired when a node's ad related state changes."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Affected_by_starting_styles_flag_updated = struct
  let name = "DOM.affectedByStartingStylesFlagUpdated"

  type params = {
    node_id : Cdp_base.Dom.Node_id.t; [@key "nodeId"] [@ocaml.doc "The id of the node."]
    affected_by_starting_styles : bool; [@key "affectedByStartingStyles"] [@ocaml.doc "If the node has starting styles."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Fired when a node's starting styles changes."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Pseudo_element_removed = struct
  let name = "DOM.pseudoElementRemoved"

  type params = {
    parent_id : Cdp_base.Dom.Node_id.t; [@key "parentId"] [@ocaml.doc "Pseudo element's parent element id."]
    pseudo_element_id : Cdp_base.Dom.Node_id.t; [@key "pseudoElementId"] [@ocaml.doc "The removed pseudo element id."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Called when a pseudo element is removed from an element."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_child_nodes = struct
  let name = "DOM.setChildNodes"

  type params = {
    parent_id : Cdp_base.Dom.Node_id.t; [@key "parentId"] [@ocaml.doc "Parent node id to populate with children."]
    nodes : node list; [@key "nodes"] [@ocaml.doc "Child nodes array."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc
  "Fired when backend wants to provide client with the missing DOM structure. This happens upon\n\
   most of the calls requesting node ids."]

module Shadow_root_popped = struct
  let name = "DOM.shadowRootPopped"

  type params = {
    host_id : Cdp_base.Dom.Node_id.t; [@key "hostId"] [@ocaml.doc "Host element id."]
    root_id : Cdp_base.Dom.Node_id.t; [@key "rootId"] [@ocaml.doc "Shadow root id."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Called when shadow root is popped from the element."]
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Shadow_root_pushed = struct
  let name = "DOM.shadowRootPushed"

  type params = {
    host_id : Cdp_base.Dom.Node_id.t; [@key "hostId"] [@ocaml.doc "Host element id."]
    root : node; [@key "root"] [@ocaml.doc "Shadow root."]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@ocaml.doc "Called when shadow root is pushed into the element."]
[@@alert experimental "experimental in CDP, may change with Chrome"]
