(* Generated by cdp-gen from Chrome DevTools Protocol r1698617. DO NOT EDIT. *)

include Cdp_network_types
open Jsonkit.Primitives

module Can_clear_browser_cache = struct
  let name = "Network.canClearBrowserCache"

  type result = { result : bool [@key "result"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Can_clear_browser_cookies = struct
  let name = "Network.canClearBrowserCookies"

  type result = { result : bool [@key "result"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Can_emulate_network_conditions = struct
  let name = "Network.canEmulateNetworkConditions"

  type result = { result : bool [@key "result"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Clear_browser_cache = struct
  let name = "Network.clearBrowserCache"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Clear_browser_cookies = struct
  let name = "Network.clearBrowserCookies"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Delete_cookies = struct
  let name = "Network.deleteCookies"

  type params = {
    name : string; [@key "name"]
    url : string option; [@key "url"] [@option] [@json.drop_default]
    domain : string option; [@key "domain"] [@option] [@json.drop_default]
    path : string option; [@key "path"] [@option] [@json.drop_default]
    partition_key : cookie_partition_key option;
       [@key "partitionKey"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Disable = struct
  let name = "Network.disable"

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end

module Emulate_network_conditions = struct
  let name = "Network.emulateNetworkConditions"

  type params = {
    offline : bool; [@key "offline"]
    latency : Cdp_json.number; [@key "latency"]
    download_throughput : Cdp_json.number; [@key "downloadThroughput"]
    upload_throughput : Cdp_json.number; [@key "uploadThroughput"]
    connection_type : connection_type option; [@key "connectionType"] [@option] [@json.drop_default]
    packet_loss : Cdp_json.number option;
       [@key "packetLoss"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    packet_queue_length : int option;
       [@key "packetQueueLength"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    packet_reordering : bool option;
       [@key "packetReordering"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Emulate_network_conditions_by_rule = struct
  let name = "Network.emulateNetworkConditionsByRule"

  type params = {
    offline : bool option; [@key "offline"] [@option] [@json.drop_default] [@ocaml.deprecated "deprecated in CDP"]
    emulate_offline_service_worker : bool option; [@key "emulateOfflineServiceWorker"] [@option] [@json.drop_default]
    matched_network_conditions : network_conditions list; [@key "matchedNetworkConditions"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { rule_ids : string list [@key "ruleIds"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Override_network_state = struct
  let name = "Network.overrideNetworkState"

  type params = {
    offline : bool; [@key "offline"]
    latency : Cdp_json.number; [@key "latency"]
    download_throughput : Cdp_json.number; [@key "downloadThroughput"]
    upload_throughput : Cdp_json.number; [@key "uploadThroughput"]
    connection_type : connection_type option; [@key "connectionType"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Enable = struct
  let name = "Network.enable"

  type params = {
    max_total_buffer_size : int option;
       [@key "maxTotalBufferSize"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    max_resource_buffer_size : int option;
       [@key "maxResourceBufferSize"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    max_post_data_size : int option; [@key "maxPostDataSize"] [@option] [@json.drop_default]
    report_direct_socket_traffic : bool option;
       [@key "reportDirectSocketTraffic"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    enable_durable_messages : bool option;
       [@key "enableDurableMessages"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Configure_durable_messages = struct
  let name = "Network.configureDurableMessages"

  type params = {
    max_total_buffer_size : int option; [@key "maxTotalBufferSize"] [@option] [@json.drop_default]
    max_resource_buffer_size : int option; [@key "maxResourceBufferSize"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_all_cookies = struct
  let name = "Network.getAllCookies"

  type result = { cookies : cookie list [@key "cookies"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
end
[@@ocaml.deprecated "deprecated in CDP"]

module Get_certificate = struct
  let name = "Network.getCertificate"

  type params = { origin : string [@key "origin"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { table_names : string list [@key "tableNames"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_cookies = struct
  let name = "Network.getCookies"

  type params = { urls : string list option [@key "urls"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { cookies : cookie list [@key "cookies"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_response_body = struct
  let name = "Network.getResponseBody"

  type params = { request_id : Cdp_base.Network.Request_id.t [@key "requestId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    body : string; [@key "body"]
    base64_encoded : bool; [@key "base64Encoded"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Get_request_post_data = struct
  let name = "Network.getRequestPostData"

  type params = { request_id : Cdp_base.Network.Request_id.t [@key "requestId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = {
    post_data : string; [@key "postData"]
    base64_encoded : bool; [@key "base64Encoded"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Replay_xhr = struct
  let name = "Network.replayXHR"

  type params = { request_id : Cdp_base.Network.Request_id.t [@key "requestId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Search_in_response_body = struct
  let name = "Network.searchInResponseBody"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    query : string; [@key "query"]
    case_sensitive : bool option; [@key "caseSensitive"] [@option] [@json.drop_default]
    is_regex : bool option; [@key "isRegex"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { result : Cdp_debugger_types.search_match list [@key "result"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_blocked_ur_ls = struct
  let name = "Network.setBlockedURLs"

  type params = {
    url_patterns : block_pattern list option; [@key "urlPatterns"] [@option] [@json.drop_default]
    urls : string list option; [@key "urls"] [@option] [@json.drop_default] [@ocaml.deprecated "deprecated in CDP"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_bypass_service_worker = struct
  let name = "Network.setBypassServiceWorker"

  type params = { bypass : bool [@key "bypass"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_cache_disabled = struct
  let name = "Network.setCacheDisabled"

  type params = { cache_disabled : bool [@key "cacheDisabled"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_cookie = struct
  let name = "Network.setCookie"

  type params = {
    name : string; [@key "name"]
    value : string; [@key "value"]
    url : string option; [@key "url"] [@option] [@json.drop_default]
    domain : string option; [@key "domain"] [@option] [@json.drop_default]
    path : string option; [@key "path"] [@option] [@json.drop_default]
    secure : bool option; [@key "secure"] [@option] [@json.drop_default]
    http_only : bool option; [@key "httpOnly"] [@option] [@json.drop_default]
    same_site : cookie_same_site option; [@key "sameSite"] [@option] [@json.drop_default]
    expires : Cdp_base.Network.Time_since_epoch.t option; [@key "expires"] [@option] [@json.drop_default]
    priority : cookie_priority option;
       [@key "priority"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    source_scheme : cookie_source_scheme option;
       [@key "sourceScheme"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    source_port : int option;
       [@key "sourcePort"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    partition_key : cookie_partition_key option;
       [@key "partitionKey"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { success : bool [@key "success"] [@ocaml.deprecated "deprecated in CDP"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_cookies = struct
  let name = "Network.setCookies"

  type params = { cookies : cookie_param list [@key "cookies"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_extra_http_headers = struct
  let name = "Network.setExtraHTTPHeaders"

  type params = { headers : headers [@key "headers"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end

module Set_attach_debug_stack = struct
  let name = "Network.setAttachDebugStack"

  type params = { enabled : bool [@key "enabled"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_user_agent_override = struct
  let name = "Network.setUserAgentOverride"

  type params = {
    user_agent : string; [@key "userAgent"]
    accept_language : string option; [@key "acceptLanguage"] [@option] [@json.drop_default]
    platform : string option; [@key "platform"] [@option] [@json.drop_default]
    user_agent_metadata : Cdp_emulation_types.user_agent_metadata option;
       [@key "userAgentMetadata"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert redirected "redirected to the Emulation domain in CDP"]

module Stream_resource_content = struct
  let name = "Network.streamResourceContent"

  type params = { request_id : Cdp_base.Network.Request_id.t [@key "requestId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { buffered_data : string [@key "bufferedData"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Get_security_isolation_status = struct
  let name = "Network.getSecurityIsolationStatus"

  type params = { frame_id : Cdp_base.Page.Frame_id.t option [@key "frameId"] [@option] [@json.drop_default] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { status : security_isolation_status [@key "status"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Enable_reporting_api = struct
  let name = "Network.enableReportingApi"

  type params = { enable : bool [@key "enable"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Enable_device_bound_sessions = struct
  let name = "Network.enableDeviceBoundSessions"

  type params = { enable : bool [@key "enable"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Delete_device_bound_session = struct
  let name = "Network.deleteDeviceBoundSession"

  type params = { key : device_bound_session_key [@key "key"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Fetch_schemeful_site = struct
  let name = "Network.fetchSchemefulSite"

  type params = { origin : string [@key "origin"] } [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { schemeful_site : string [@key "schemefulSite"] } [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Load_network_resource = struct
  let name = "Network.loadNetworkResource"

  type params = {
    frame_id : Cdp_base.Page.Frame_id.t option; [@key "frameId"] [@option] [@json.drop_default]
    url : string; [@key "url"]
    options : load_network_resource_options; [@key "options"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = { resource : load_network_resource_page_result [@key "resource"] }
  [@@allow_extra_fields] [@@deriving json, show, eq]

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Set_cookie_controls = struct
  let name = "Network.setCookieControls"

  type params = { enable_third_party_cookie_restriction : bool [@key "enableThirdPartyCookieRestriction"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  type result = unit [@@deriving show, eq]

  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()

  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Data_received = struct
  let name = "Network.dataReceived"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    data_length : int; [@key "dataLength"]
    encoded_data_length : int; [@key "encodedDataLength"]
    data : string option;
       [@key "data"] [@option] [@json.drop_default] [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Event_source_message_received = struct
  let name = "Network.eventSourceMessageReceived"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    event_name : string; [@key "eventName"]
    event_id : string; [@key "eventId"]
    data : string; [@key "data"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Loading_failed = struct
  let name = "Network.loadingFailed"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    type_ : resource_type; [@key "type"]
    error_text : string; [@key "errorText"]
    canceled : bool option; [@key "canceled"] [@option] [@json.drop_default]
    blocked_reason : blocked_reason option; [@key "blockedReason"] [@option] [@json.drop_default]
    cors_error_status : cors_error_status option; [@key "corsErrorStatus"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Loading_finished = struct
  let name = "Network.loadingFinished"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    encoded_data_length : Cdp_json.number; [@key "encodedDataLength"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Request_served_from_cache = struct
  let name = "Network.requestServedFromCache"

  type params = { request_id : Cdp_base.Network.Request_id.t [@key "requestId"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Request_will_be_sent = struct
  let name = "Network.requestWillBeSent"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    loader_id : Cdp_base.Network.Loader_id.t; [@key "loaderId"]
    document_url : string; [@key "documentURL"]
    request : request; [@key "request"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    wall_time : Cdp_base.Network.Time_since_epoch.t; [@key "wallTime"]
    initiator : initiator; [@key "initiator"]
    redirect_has_extra_info : bool;
       [@key "redirectHasExtraInfo"] [@alert experimental "experimental in CDP, may change with Chrome"]
    redirect_response : response option; [@key "redirectResponse"] [@option] [@json.drop_default]
    type_ : resource_type option; [@key "type"] [@option] [@json.drop_default]
    frame_id : Cdp_base.Page.Frame_id.t option; [@key "frameId"] [@option] [@json.drop_default]
    has_user_gesture : bool option; [@key "hasUserGesture"] [@option] [@json.drop_default]
    render_blocking_behavior : render_blocking_behavior option;
       [@key "renderBlockingBehavior"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Resource_changed_priority = struct
  let name = "Network.resourceChangedPriority"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    new_priority : resource_priority; [@key "newPriority"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Signed_exchange_received = struct
  let name = "Network.signedExchangeReceived"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    info : signed_exchange_info; [@key "info"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Response_received = struct
  let name = "Network.responseReceived"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    loader_id : Cdp_base.Network.Loader_id.t; [@key "loaderId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    type_ : resource_type; [@key "type"]
    response : response; [@key "response"]
    has_extra_info : bool; [@key "hasExtraInfo"] [@alert experimental "experimental in CDP, may change with Chrome"]
    frame_id : Cdp_base.Page.Frame_id.t option; [@key "frameId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Web_socket_closed = struct
  let name = "Network.webSocketClosed"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Web_socket_created = struct
  let name = "Network.webSocketCreated"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    url : string; [@key "url"]
    initiator : initiator option; [@key "initiator"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Web_socket_frame_error = struct
  let name = "Network.webSocketFrameError"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    error_message : string; [@key "errorMessage"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Web_socket_frame_received = struct
  let name = "Network.webSocketFrameReceived"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    response : web_socket_frame; [@key "response"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Web_socket_frame_sent = struct
  let name = "Network.webSocketFrameSent"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    response : web_socket_frame; [@key "response"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Web_socket_handshake_response_received = struct
  let name = "Network.webSocketHandshakeResponseReceived"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    response : web_socket_response; [@key "response"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Web_socket_will_send_handshake_request = struct
  let name = "Network.webSocketWillSendHandshakeRequest"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    wall_time : Cdp_base.Network.Time_since_epoch.t; [@key "wallTime"]
    request : web_socket_request; [@key "request"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Web_transport_created = struct
  let name = "Network.webTransportCreated"

  type params = {
    transport_id : Cdp_base.Network.Request_id.t; [@key "transportId"]
    url : string; [@key "url"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    initiator : initiator option; [@key "initiator"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Web_transport_connection_established = struct
  let name = "Network.webTransportConnectionEstablished"

  type params = {
    transport_id : Cdp_base.Network.Request_id.t; [@key "transportId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Web_transport_closed = struct
  let name = "Network.webTransportClosed"

  type params = {
    transport_id : Cdp_base.Network.Request_id.t; [@key "transportId"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end

module Direct_tcp_socket_created = struct
  let name = "Network.directTCPSocketCreated"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    remote_addr : string; [@key "remoteAddr"]
    remote_port : int; [@key "remotePort"]
    options : direct_tcp_socket_options; [@key "options"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    initiator : initiator option; [@key "initiator"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_tcp_socket_opened = struct
  let name = "Network.directTCPSocketOpened"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    remote_addr : string; [@key "remoteAddr"]
    remote_port : int; [@key "remotePort"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    local_addr : string option; [@key "localAddr"] [@option] [@json.drop_default]
    local_port : int option; [@key "localPort"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_tcp_socket_aborted = struct
  let name = "Network.directTCPSocketAborted"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    error_message : error_reason; [@key "errorMessage"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_tcp_socket_closed = struct
  let name = "Network.directTCPSocketClosed"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_tcp_socket_chunk_sent = struct
  let name = "Network.directTCPSocketChunkSent"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    data : string; [@key "data"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_tcp_socket_chunk_received = struct
  let name = "Network.directTCPSocketChunkReceived"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    data : string; [@key "data"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_udp_socket_joined_multicast_group = struct
  let name = "Network.directUDPSocketJoinedMulticastGroup"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    ip_address : string; [@key "IPAddress"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_udp_socket_left_multicast_group = struct
  let name = "Network.directUDPSocketLeftMulticastGroup"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    ip_address : string; [@key "IPAddress"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_udp_socket_created = struct
  let name = "Network.directUDPSocketCreated"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    options : direct_udp_socket_options; [@key "options"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    initiator : initiator option; [@key "initiator"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_udp_socket_opened = struct
  let name = "Network.directUDPSocketOpened"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    local_addr : string; [@key "localAddr"]
    local_port : int; [@key "localPort"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
    remote_addr : string option; [@key "remoteAddr"] [@option] [@json.drop_default]
    remote_port : int option; [@key "remotePort"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_udp_socket_aborted = struct
  let name = "Network.directUDPSocketAborted"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    error_message : error_reason; [@key "errorMessage"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_udp_socket_closed = struct
  let name = "Network.directUDPSocketClosed"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_udp_socket_chunk_sent = struct
  let name = "Network.directUDPSocketChunkSent"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    message : direct_udp_message; [@key "message"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Direct_udp_socket_chunk_received = struct
  let name = "Network.directUDPSocketChunkReceived"

  type params = {
    identifier : Cdp_base.Network.Request_id.t; [@key "identifier"]
    message : direct_udp_message; [@key "message"]
    timestamp : Cdp_base.Network.Monotonic_time.t; [@key "timestamp"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Request_will_be_sent_extra_info = struct
  let name = "Network.requestWillBeSentExtraInfo"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    associated_cookies : associated_cookie list; [@key "associatedCookies"]
    headers : headers; [@key "headers"]
    connect_timing : connect_timing;
       [@key "connectTiming"] [@alert experimental "experimental in CDP, may change with Chrome"]
    device_bound_session_usages : device_bound_session_with_usage list option;
       [@key "deviceBoundSessionUsages"] [@option] [@json.drop_default]
    client_security_state : client_security_state option; [@key "clientSecurityState"] [@option] [@json.drop_default]
    site_has_cookie_in_other_partition : bool option;
       [@key "siteHasCookieInOtherPartition"] [@option] [@json.drop_default]
    applied_network_conditions_id : string option; [@key "appliedNetworkConditionsId"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Response_received_extra_info = struct
  let name = "Network.responseReceivedExtraInfo"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    blocked_cookies : blocked_set_cookie_with_reason list; [@key "blockedCookies"]
    headers : headers; [@key "headers"]
    resource_ip_address_space : ip_address_space; [@key "resourceIPAddressSpace"]
    status_code : int; [@key "statusCode"]
    headers_text : string option; [@key "headersText"] [@option] [@json.drop_default]
    cookie_partition_key : cookie_partition_key option;
       [@key "cookiePartitionKey"]
       [@option]
       [@json.drop_default]
       [@alert experimental "experimental in CDP, may change with Chrome"]
    cookie_partition_key_opaque : bool option; [@key "cookiePartitionKeyOpaque"] [@option] [@json.drop_default]
    exempted_cookies : exempted_set_cookie_with_reason list option;
       [@key "exemptedCookies"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Response_received_early_hints = struct
  let name = "Network.responseReceivedEarlyHints"

  type params = {
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    headers : headers; [@key "headers"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Trust_token_operation_done = struct
  let name = "Network.trustTokenOperationDone"

  type status =
    | Ok_ [@json.name "Ok"]
    | InvalidArgument [@json.name "InvalidArgument"]
    | MissingIssuerKeys [@json.name "MissingIssuerKeys"]
    | FailedPrecondition [@json.name "FailedPrecondition"]
    | ResourceExhausted [@json.name "ResourceExhausted"]
    | AlreadyExists [@json.name "AlreadyExists"]
    | ResourceLimited [@json.name "ResourceLimited"]
    | Unauthorized [@json.name "Unauthorized"]
    | BadResponse [@json.name "BadResponse"]
    | InternalError [@json.name "InternalError"]
    | UnknownError [@json.name "UnknownError"]
    | FulfilledLocally [@json.name "FulfilledLocally"]
    | SiteIssuerLimit [@json.name "SiteIssuerLimit"]
    | Other of Cdp_json.unknown [@json.catch_all]
  [@@compact_variants] [@@deriving json, show, eq]

  type params = {
    status : status; [@key "status"]
    type_ : trust_token_operation_type; [@key "type"]
    request_id : Cdp_base.Network.Request_id.t; [@key "requestId"]
    top_level_origin : string option; [@key "topLevelOrigin"] [@option] [@json.drop_default]
    issuer_origin : string option; [@key "issuerOrigin"] [@option] [@json.drop_default]
    issued_token_count : int option; [@key "issuedTokenCount"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Policy_updated = struct
  let name = "Network.policyUpdated"

  type params = unit [@@deriving show, eq]

  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Reporting_api_report_added = struct
  let name = "Network.reportingApiReportAdded"

  type params = { report : reporting_api_report [@key "report"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Reporting_api_report_updated = struct
  let name = "Network.reportingApiReportUpdated"

  type params = { report : reporting_api_report [@key "report"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Reporting_api_endpoints_changed_for_origin = struct
  let name = "Network.reportingApiEndpointsChangedForOrigin"

  type params = {
    origin : string; [@key "origin"]
    endpoints : reporting_api_endpoint list; [@key "endpoints"]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Device_bound_sessions_added = struct
  let name = "Network.deviceBoundSessionsAdded"

  type params = { sessions : device_bound_session list [@key "sessions"] }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]

module Device_bound_session_event_occurred = struct
  let name = "Network.deviceBoundSessionEventOccurred"

  type params = {
    event_id : Cdp_base.Network.Device_bound_session_event_id.t; [@key "eventId"]
    site : string; [@key "site"]
    succeeded : bool; [@key "succeeded"]
    session_id : string option; [@key "sessionId"] [@option] [@json.drop_default]
    creation_event_details : creation_event_details option; [@key "creationEventDetails"] [@option] [@json.drop_default]
    refresh_event_details : refresh_event_details option; [@key "refreshEventDetails"] [@option] [@json.drop_default]
    termination_event_details : termination_event_details option;
       [@key "terminationEventDetails"] [@option] [@json.drop_default]
    challenge_event_details : challenge_event_details option;
       [@key "challengeEventDetails"] [@option] [@json.drop_default]
  }
  [@@allow_extra_fields] [@@deriving json, show, eq, make]

  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
end
[@@alert experimental "experimental in CDP, may change with Chrome"]
