Commands and events become submodules. A command with params and returns gets
params + result records; a zero-return command gets result = unit; an event
gets params and its wire name.

  $ cat > browser.json << 'EOF'
  > {"domains":[{"domain":"Demo","commands":[
  >   {"name":"getItem","parameters":[
  >     {"name":"itemId","type":"string"}
  >   ],"returns":[
  >     {"name":"found","type":"boolean"}
  >   ]},
  >   {"name":"reset"}
  > ],"events":[
  >   {"name":"itemChanged","parameters":[
  >     {"name":"itemId","type":"string"}
  >   ]},
  >   {"name":"resetDone"}
  > ]}]}
  > EOF
  $ echo '{"domains":[]}' > js.json
  $ mkdir out && cdp-gen generate browser.json js.json out Demo
  wrote glue: cdp_json.ml, cdp_command.ml, cdp_event.ml, cdp_envelope.ml
  generated cdp_base.ml: 0 sealed alias modules
  generated cdp_demo(_types).ml: 0 types, 2 commands, 2 events
  generated cdp.ml index (1 domains, protocol unknown)
  $ cat out/cdp_demo.ml
  (* Generated by cdp-gen from Chrome DevTools Protocol unknown. DO NOT EDIT. *)
  
  include Cdp_demo_types
  open Jsonkit.Primitives
  
  module Get_item = struct
  let name = "Demo.getItem"
  
  
  type params = {
    item_id : string [@key "itemId"];
  }
  [@@allow_extra_fields]
  [@@deriving json, show, eq, make]
  
  
  type result = {
    found : bool [@key "found"];
  }
  [@@allow_extra_fields]
  [@@deriving json, show, eq]
  
  let command params : result Cdp_command.t =
    { Cdp_command.name; params = Some (params_to_json params); parse = result_of_json }
  
  end
  
  module Reset = struct
  let name = "Demo.reset"
  
  type result = unit [@@deriving show, eq]
  
  let result_of_json (_ignored_payload : Cdp_json.t) : result = ()
  
  let command : result Cdp_command.t = { Cdp_command.name; params = None; parse = result_of_json }
  
  end
  
  module Item_changed = struct
  let name = "Demo.itemChanged"
  
  
  type params = {
    item_id : string [@key "itemId"];
  }
  [@@allow_extra_fields]
  [@@deriving json, show, eq, make]
  
  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
  
  end
  
  module Reset_done = struct
  let name = "Demo.resetDone"
  
  type params = unit [@@deriving show, eq]
  
  let params_of_json (_ignored_payload : Cdp_json.t) : params = ()
  
  let event : params Cdp_event.t = { Cdp_event.name; parse = params_of_json }
  
  end
  
