The roundtrip subcommand writes a standalone test file with schema-driven
encode/decode checks for every generated type.

  $ cat > browser.json << 'EOF'
  > {"domains":[{"domain":"Demo","types":[
  >   {"id":"Mood","type":"string","enum":["happy","sad"]},
  >   {"id":"Point","type":"object","properties":[
  >     {"name":"x","type":"integer"},
  >     {"name":"y","type":"number","optional":true}
  >   ]}
  > ]}]}
  > EOF
  $ echo '{"domains":[]}' > js.json
  $ cdp-gen roundtrip browser.json js.json roundtrip_out.ml Demo
  generated roundtrip_out.ml: 2 roundtrip checks, 0 skipped
  $ cat roundtrip_out.ml
  (* Generated by cdp-gen from Chrome DevTools Protocol unknown. DO NOT EDIT. *)
  
  (* Roundtrip tests over every generated type: decode a sample synthesized
     from the protocol schema, encode it back, decode again, and compare. *)
  
  let failures = ref 0
  
  let check name of_json to_json equal raw =
    let json = Yojson.Basic.from_string raw in
    let decoded = of_json json in
    let encoded = to_json decoded in
    let redecoded = of_json encoded in
    match equal decoded redecoded with
    | true -> ()
    | false ->
      incr failures;
      Printf.printf "FAIL %s: value changed after an encode/decode roundtrip\n" name
  
  let () = check "Demo.Mood" Cdp.Demo.mood_of_json Cdp.Demo.mood_to_json Cdp.Demo.equal_mood "\"happy\""
  let () = check "Demo.Point" Cdp.Demo.point_of_json Cdp.Demo.point_to_json Cdp.Demo.equal_point "{\"x\":7}"
  
  let () =
    match !failures with
    | 0 -> print_endline "all roundtrip tests passed"
    | count -> failwith (Printf.sprintf "%d roundtrip failures" count)

A type whose required fields cycle back to itself has no finite sample; it
is skipped loudly instead of looping forever, and no check is emitted.

  $ cat > browser.json << 'EOF2'
  > {"domains":[{"domain":"Demo","types":[
  >   {"id":"Tree","type":"object","properties":[
  >     {"name":"children","type":"array","items":{"$ref":"Tree"}}
  >   ]}
  > ]}]}
  > EOF2
  $ cdp-gen roundtrip browser.json js.json tree_out.ml Demo
  generated tree_out.ml: 0 roundtrip checks, 1 skipped
  skipped Demo.Tree: cdp-gen: required-field cycle through Demo.Tree
  $ grep "let () = check" tree_out.ml
  [1]
