(executable
 (name navigate)
 (modules navigate)
 (libraries cdp cdp_lwt lwt lwt.unix)
 (preprocess
  (pps lwt_ppx)))

(executable
 (name render)
 (modules render)
 (libraries cdp cdp_lwt lwt lwt.unix)
 (preprocess
  (pps lwt_ppx)))

(executable
 (name screenshot)
 (modules screenshot)
 (libraries cdp cdp_lwt lwt lwt.unix base64 unix)
 (preprocess
  (pps lwt_ppx)))

(executable
 (name attach)
 (modules attach)
 (libraries cdp cdp_lwt lwt lwt.unix base64 unix)
 (preprocess
  (pps lwt_ppx)))

(executable
 (name tail)
 (modules tail)
 (libraries cdp cdp_lwt lwt lwt.unix yojson)
 (preprocess
  (pps lwt_ppx)))
